use crate::models::{AstroBody, AstroSign};

pub fn build_signs() -> Vec<AstroSign> {
    vec![
        AstroSign {
            id: 0,
            name: "Aries".into(),
            dates: "Mar 21 – Apr 19".into(),
            element: "Fire".into(),
            modality: "Cardinal".into(),
            ruler: "Mars".into(),
            symbol: "\u{2648}".into(),
            traits: vec!["bold".into(), "pioneering".into(), "hot-headed".into(), "direct".into()],
            body_part: "head and face".into(),
            description: "The first sign of the zodiac: the spark, the ram that charges first and thinks later. Aries energy is ignition — raw will, courage, and the urge to begin.".into(),
            compatibility: vec!["Leo".into(), "Sagittarius".into(), "Gemini".into(), "Aquarius".into()],
            magic_notes: "Candle magic for courage, new beginnings, banishing hesitation. Ruled by Mars — best on a Tuesday.".into(),
            is_custom: false,
        },
        AstroSign {
            id: 1,
            name: "Taurus".into(),
            dates: "Apr 20 – May 20".into(),
            element: "Earth".into(),
            modality: "Fixed".into(),
            ruler: "Venus".into(),
            symbol: "\u{2649}".into(),
            traits: vec!["steady".into(), "sensual".into(), "stubborn".into(), "grounded".into()],
            body_part: "throat and neck".into(),
            description: "The bull: patience, pleasure, and permanence. Taurus builds slowly and holds what it builds — the sign of the green thumb and the full pantry.".into(),
            compatibility: vec!["Virgo".into(), "Capricorn".into(), "Cancer".into(), "Pisces".into()],
            magic_notes: "Prosperity, grounding, and glamours of composure. Ruled by Venus — best on a Friday.".into(),
            is_custom: false,
        },
        AstroSign {
            id: 2,
            name: "Gemini".into(),
            dates: "May 21 – Jun 20".into(),
            element: "Air".into(),
            modality: "Mutable".into(),
            ruler: "Mercury".into(),
            symbol: "\u{264A}".into(),
            traits: vec!["curious".into(), "witty".into(), "restless".into(), "adaptable".into()],
            body_part: "hands, lungs, nervous system".into(),
            description: "The twins: the quicksilver mind. Gemini collects ideas the way magpies collect shine, and speaks them faster than most can follow.".into(),
            compatibility: vec!["Libra".into(), "Aquarius".into(), "Aries".into(), "Leo".into()],
            magic_notes: "Charm bags for communication, sigils for learning, workings of diplomacy. Ruled by Mercury — best on a Wednesday.".into(),
            is_custom: false,
        },
        AstroSign {
            id: 3,
            name: "Cancer".into(),
            dates: "Jun 21 – Jul 22".into(),
            element: "Water".into(),
            modality: "Cardinal".into(),
            ruler: "Moon".into(),
            symbol: "\u{264B}".into(),
            traits: vec!["nurturing".into(), "protective".into(), "moody".into(), "intuitive".into()],
            body_part: "chest and stomach".into(),
            description: "The crab: soft inside the shell. Cancer is memory, home, and the fierce tenderness of the tide — everything that protects and remembers.".into(),
            compatibility: vec!["Scorpio".into(), "Pisces".into(), "Taurus".into(), "Virgo".into()],
            magic_notes: "Hearth blessings, dream work, ancestral offerings. Ruled by the Moon — best on a Monday.".into(),
            is_custom: false,
        },
        AstroSign {
            id: 4,
            name: "Leo".into(),
            dates: "Jul 23 – Aug 22".into(),
            element: "Fire".into(),
            modality: "Fixed".into(),
            ruler: "Sun".into(),
            symbol: "\u{264C}".into(),
            traits: vec!["radiant".into(), "proud".into(), "generous".into(), "dramatic".into()],
            body_part: "heart and spine".into(),
            description: "The lion: sovereignty made flesh. Leo does not ask to be seen — it shines whether watched or not, and warms whatever court it keeps.".into(),
            compatibility: vec!["Aries".into(), "Sagittarius".into(), "Gemini".into(), "Libra".into()],
            magic_notes: "Solar rites, confidence glamours, blessings of success. Ruled by the Sun — best on a Sunday.".into(),
            is_custom: false,
        },
        AstroSign {
            id: 5,
            name: "Virgo".into(),
            dates: "Aug 23 – Sep 22".into(),
            element: "Earth".into(),
            modality: "Mutable".into(),
            ruler: "Mercury".into(),
            symbol: "\u{264D}".into(),
            traits: vec!["precise".into(), "devoted".into(), "anxious".into(), "practical".into()],
            body_part: "digestive system".into(),
            description: "The maiden: the sacred craftsperson. Virgo sanctifies the small things — clean floors, honest drafts, tinctures measured exactly right.".into(),
            compatibility: vec!["Taurus".into(), "Capricorn".into(), "Cancer".into(), "Scorpio".into()],
            magic_notes: "Healing charms, candle dressing for health, workings of order. Ruled by Mercury — best on a Wednesday.".into(),
            is_custom: false,
        },
        AstroSign {
            id: 6,
            name: "Libra".into(),
            dates: "Sep 23 – Oct 22".into(),
            element: "Air".into(),
            modality: "Cardinal".into(),
            ruler: "Venus".into(),
            symbol: "\u{264E}".into(),
            traits: vec!["fair-minded".into(), "charming".into(), "indecisive".into(), "harmonising".into()],
            body_part: "kidneys and lower back".into(),
            description: "The scales: the diplomat of the zodiac. Libra weighs every side, loves beauty, and cannot rest while something is out of balance.".into(),
            compatibility: vec!["Gemini".into(), "Aquarius".into(), "Leo".into(), "Sagittarius".into()],
            magic_notes: "Justice workings, reconciliation spells, beauty rituals. Ruled by Venus — best on a Friday.".into(),
            is_custom: false,
        },
        AstroSign {
            id: 7,
            name: "Scorpio".into(),
            dates: "Oct 23 – Nov 21".into(),
            element: "Water".into(),
            modality: "Fixed".into(),
            ruler: "Mars".into(),
            symbol: "\u{264F}".into(),
            traits: vec!["intense".into(), "perceptive".into(), "secretive".into(), "transformative".into()],
            body_part: "reproductive organs".into(),
            description: "The scorpion: the still water that runs deep. Scorpio rules what is hidden — sex, death, secrets, and the power that comes from surviving all three.".into(),
            compatibility: vec!["Cancer".into(), "Pisces".into(), "Virgo".into(), "Capricorn".into()],
            magic_notes: "Shadow work, banishing, karmic bindings, protection of secrets. Ruled by Mars — best on a Tuesday.".into(),
            is_custom: false,
        },
        AstroSign {
            id: 8,
            name: "Sagittarius".into(),
            dates: "Nov 22 – Dec 21".into(),
            element: "Fire".into(),
            modality: "Mutable".into(),
            ruler: "Jupiter".into(),
            symbol: "\u{2650}".into(),
            traits: vec!["adventurous".into(), "philosophical".into(), "blunt".into(), "optimistic".into()],
            body_part: "hips and thighs".into(),
            description: "The archer: arrow aimed past every horizon. Sagittarius seeks truth on the road, in the argument, at the far edge of the map.".into(),
            compatibility: vec!["Aries".into(), "Leo".into(), "Libra".into(), "Aquarius".into()],
            magic_notes: "Travel charms, luck-drawing, workings of expansion. Ruled by Jupiter — best on a Thursday.".into(),
            is_custom: false,
        },
        AstroSign {
            id: 9,
            name: "Capricorn".into(),
            dates: "Dec 22 – Jan 19".into(),
            element: "Earth".into(),
            modality: "Cardinal".into(),
            ruler: "Saturn".into(),
            symbol: "\u{2651}".into(),
            traits: vec!["ambitious".into(), "disciplined".into(), "responsible".into(), "wry".into()],
            body_part: "bones and knees".into(),
            description: "The sea-goat: the mountain climber. Capricorn endures what others abandon, and builds stone by stone the life others only describe.".into(),
            compatibility: vec!["Taurus".into(), "Virgo".into(), "Scorpio".into(), "Pisces".into()],
            magic_notes: "Bindings of discipline, banishing of bad habits, long-haul prosperity. Ruled by Saturn — best on a Saturday.".into(),
            is_custom: false,
        },
        AstroSign {
            id: 10,
            name: "Aquarius".into(),
            dates: "Jan 20 – Feb 18".into(),
            element: "Air".into(),
            modality: "Fixed".into(),
            ruler: "Saturn".into(),
            symbol: "\u{2652}".into(),
            traits: vec!["visionary".into(), "detached".into(), "humanitarian".into(), "contrarian".into()],
            body_part: "ankles and circulation".into(),
            description: "The water-bearer: the stranger future demands. Aquarius pours out old orders and calls the next world in — community, invention, strange kinds of love.".into(),
            compatibility: vec!["Gemini".into(), "Libra".into(), "Aries".into(), "Sagittarius".into()],
            magic_notes: "Workings for community, breaking convention, storm magic. Ruled by Saturn (classically) — best on a Saturday.".into(),
            is_custom: false,
        },
        AstroSign {
            id: 11,
            name: "Pisces".into(),
            dates: "Feb 19 – Mar 20".into(),
            element: "Water".into(),
            modality: "Mutable".into(),
            ruler: "Jupiter".into(),
            symbol: "\u{2653}".into(),
            traits: vec!["dreamy".into(), "compassionate".into(), "porous".into(), "artistic".into()],
            body_part: "feet and lymphatic system".into(),
            description: "The fish: two currents at once, waking and dreaming. Pisces stands at the veil, feeling everything before language arrives to name it.".into(),
            compatibility: vec!["Cancer".into(), "Scorpio".into(), "Taurus".into(), "Capricorn".into()],
            magic_notes: "Dream pillow work, spirit contact, scrying, sea offerings. Ruled by Jupiter (trad.) — best on a Thursday.".into(),
            is_custom: false,
        },
        AstroSign {
            id: 12,
            name: "Ophiuchus".into(),
            dates: "Nov 30 – Dec 18 (overlaps Sagittarius)".into(),
            element: "Aether".into(),
            modality: "Fixed".into(),
            ruler: "Chiron".into(),
            symbol: "\u{26CE}".into(),
            traits: vec!["healing".into(), "serpentine".into(), "seeker".into(), "liminal".into()],
            body_part: "hands and the spine's serpentine current".into(),
            description: "The serpent-bearer: the thirteenth sign that wasn't. The healer who wrestles the snake and learns its venom. A sign for those who walk between.".into(),
            compatibility: vec!["Cancer".into(), "Scorpio".into(), "Pisces".into(), "Virgo".into()],
            magic_notes: "Healing work, kundalini and serpent current work, herb lore of venom and cure. No classical ruler — work with the serpent directly.".into(),
            is_custom: false,
        },
    ]
}

pub fn build_bodies() -> Vec<AstroBody> {
    vec![
        AstroBody {
            id: 0,
            name: "Sun".into(),
            symbol: "\u{2609}".into(),
            day: "Sunday".into(),
            domain: "identity, vitality, success, sovereignty".into(),
            description: "The self at its centre: will, radiance, and the sovereign spark. In magic the Sun governs success, healing of the whole person, confidence, and oaths sworn in daylight.".into(),
            color_note: "gold, orange, amber".into(),
            is_custom: false,
        },
        AstroBody {
            id: 1,
            name: "Moon".into(),
            symbol: "\u{263D}".into(),
            day: "Monday".into(),
            domain: "emotion, intuition, dreams, tides, memory".into(),
            description: "The mirror that never stops changing. The Moon governs dream work, divination, the ancestors, all waters — and the timing of nearly every working, waxing to build, waning to release.".into(),
            color_note: "silver, white, pearl".into(),
            is_custom: false,
        },
        AstroBody {
            id: 2,
            name: "Mercury".into(),
            symbol: "\u{263F}".into(),
            day: "Wednesday".into(),
            domain: "communication, trickery, travel, commerce, learning".into(),
            description: "The swift messenger and the crossroads thief. Mercury governs speech, writing, bargaining, safe travel, and every working that moves information between worlds.".into(),
            color_note: "orange, mixed hues, quicksilver".into(),
            is_custom: false,
        },
        AstroBody {
            id: 3,
            name: "Venus".into(),
            symbol: "\u{2640}".into(),
            day: "Friday".into(),
            domain: "love, beauty, pleasure, art, friendship".into(),
            description: "The morning and evening star. Venus governs love in every register, attraction, the arts, reconciliation, and the gentle magnetic power of being desirable and kind.".into(),
            color_note: "rose, sea-green, copper".into(),
            is_custom: false,
        },
        AstroBody {
            id: 4,
            name: "Mars".into(),
            symbol: "\u{2642}".into(),
            day: "Tuesday".into(),
            domain: "courage, conflict, protection, drive, severing".into(),
            description: "The red spear. Mars governs courage in the face of threats, cutting away what binds, competitive edge, protection by force, and the righteous anger that defends the vulnerable.".into(),
            color_note: "red, rust, scarlet".into(),
            is_custom: false,
        },
        AstroBody {
            id: 5,
            name: "Jupiter".into(),
            symbol: "\u{2643}".into(),
            day: "Thursday".into(),
            domain: "expansion, luck, abundance, wisdom, justice".into(),
            description: "The great benefic. Jupiter governs growth in every direction — wealth, knowledge, influence, mercy — and workings of luck, legal triumph, and generous leadership.".into(),
            color_note: "royal blue, purple, deep green".into(),
            is_custom: false,
        },
        AstroBody {
            id: 6,
            name: "Saturn".into(),
            symbol: "\u{2644}".into(),
            day: "Saturday".into(),
            domain: "limit, structure, banishing, karma, endurance".into(),
            description: "The reaper with the sickle and the teacher at the boundary. Saturn governs endings, banishing, binding, protection through walls, and the stern wisdom that only time grants.".into(),
            color_note: "black, dark brown, lead grey".into(),
            is_custom: false,
        },
    ]
}