use crate::models::{Arcana, Card, CardNumber, ContextualMeanings, Suit, Tone};

pub fn build_deck() -> Vec<Card> {
    let mut deck = Vec::with_capacity(78);
    deck.extend(major_arcana());
    deck.extend(minor_arcana());
    deck
}

fn major_arcana() -> Vec<Card> {
    macro_rules! major {
        ($id:expr, $name:expr, $roman:expr, $up:expr, $rev:expr, $kw:expr, $tone:expr, $ctx:expr) => {
            Card {
                id: $id,
                name: $name.into(),
                arcana: Arcana::Major,
                suit: Suit::None,
                number: None,
                roman_numeral: Some($roman.into()),
                upright_meaning: $up.into(),
                reversed_meaning: $rev.into(),
                keywords: $kw.iter().map(|s: &&str| s.to_string()).collect(),
                image_ref: format!("card_{:02}", $id),
                tone: $tone,
                contexts: $ctx,
            }
        };
    }

    vec![
        major!(0, "The Fool", "0",
            "Beginnings, innocence, spontaneity, a free spirit.",
            "Holding back, recklessness, risk-taking, naivety.",
            ["beginnings", "freedom", "innocence"],
            Tone::Neutral,
            ctx("A leap into the unknown. Trust the journey.",
                "Be open; a playful or unexpected meeting may spark something.",
                "Take a chance on someone new. Don’t overthink first steps.",
                "Bring spontaneity back into the bond; a fresh adventure together is favored.",
                "A risky but exciting opportunity. Learn as you go.",
                "Avoid impulse spending. Do the math before jumping in.",
                "Try a new wellness routine, but avoid reckless extremes.")),
        major!(1, "The Magician", "I",
            "Manifestation, resourcefulness, power, inspired action.",
            "Manipulation, poor planning, untapped talents.",
            ["manifestation", "power", "action"],
            Tone::Positive,
            ctx("You have the tools; focus will turn ideas into results.",
                "Charm and confidence attract attention now.",
                "You’re magnetic—use it to make the first move.",
                "A good time to co-create plans or rekindle chemistry through shared goals.",
                "Pitch, negotiate, or start the project. Your skills are enough.",
                "A financial opportunity you can actively shape. Take initiative.",
                "Your mindset affects your body; focus energy on a clear health goal.")),
        major!(2, "The High Priestess", "II",
            "Intuition, sacred knowledge, divine feminine, the subconscious.",
            "Secrets, disconnected from intuition, withdrawal, silence.",
            ["intuition", "mystery", "subconscious"],
            Tone::Neutral,
            ctx("Listen more than you speak. The answer is already within you.",
                "Read between the lines. Someone may be guarding their heart.",
                "Trust gut feelings about who is genuine; mystery can be alluring but patience is needed.",
                "Emotional intimacy deepens through quiet trust, not forced disclosure.",
                "Research and observation give you an edge before acting.",
                "Hold off on major money moves until you know the full picture.",
                "Rest, sleep, and dreams carry useful signals now.")),
        major!(3, "The Empress", "III",
            "Femininity, beauty, nature, nurturing, abundance.",
            "Creative block, dependence on others, emptiness.",
            ["abundance", "nurturing", "fertility"],
            Tone::Positive,
            ctx("Growth and sensuality flourish. Nurture what you want to bloom.",
                "Romance is warm and generous. Let yourself be cared for.",
                "Self-love attracts better matches; enjoy life and others will notice.",
                "A nurturing phase. Affection and comfort strengthen the relationship.",
                "Creative or people-oriented work thrives. Mentor or support others.",
                "Abundance flows; invest in comfort and long-term security.",
                "Nourish your body with good food, nature, and gentle movement.")),
        major!(4, "The Emperor", "IV",
            "Authority, establishment, structure, father figure.",
            "Tyranny, rigidity, coldness, excessive control.",
            ["authority", "structure", "control"],
            Tone::Neutral,
            ctx("Order and discipline create the foundation for success.",
                "Stability and clear expectations are attractive. Avoid being domineering.",
                "Look for someone reliable; avoid chaos merchants.",
                "Define roles and boundaries together. Practical plans strengthen trust.",
                "Lead, organize, or establish systems. Authority favors you.",
                "Budget, plan, and protect assets. Structure builds wealth.",
                "Discipline in routine restores strength and resilience.")),
        major!(5, "The Hierophant", "V",
            "Spiritual wisdom, religious beliefs, conformity, tradition.",
            "Personal beliefs, freedom, challenging the status quo.",
            ["tradition", "wisdom", "conformity"],
            Tone::Neutral,
            ctx("Respected structures and shared values offer guidance.",
                "Traditional courtship or shared beliefs may matter now.",
                "Community or cultural circles could introduce you to someone aligned.",
                "Shared values and rituals keep the relationship grounded.",
                "Follow established process, certification, or mentorship.",
                "Stick to conservative, proven financial strategies.",
                "Conventional care or trusted advice leads to steady recovery.")),
        major!(6, "The Lovers", "VI",
            "Love, harmony, relationships, values alignment, choices.",
            "Self-love, disharmony, imbalance, misalignment of values.",
            ["love", "harmony", "choice"],
            Tone::Positive,
            ctx("Meaningful choice. Align your head and heart.",
                "A significant connection or decision about love is highlighted.",
                "Know your values before choosing a partner; clarity attracts the right match.",
                "A moment of deepening or recommitment. Honest conversation heals.",
                "A partnership or deal requires aligned values. Choose well.",
                "Joint finances or a values-based purchase may arise.",
                "Heart health and emotional balance are intertwined; choose peace.")),
        major!(7, "The Chariot", "VII",
            "Control, willpower, success, action, determination.",
            "Self-discipline, opposition, lack of direction, aggression.",
            ["willpower", "victory", "action"],
            Tone::Positive,
            ctx("Drive and focus carry you forward. Direct your energy.",
                "Pursue what you want with confidence, but don’t run over the other person.",
                "Go after a clear goal in dating; mixed signals waste momentum.",
                "Work together toward a shared win. Avoid competing with each other.",
                "Aggressive but effective progress. Keep the goal in sight.",
                "Earn more through focused effort, but watch for impulsive spending.",
                "Physical discipline and willpower improve stamina and recovery.")),
        major!(8, "Strength", "VIII",
            "Strength, courage, persuasion, influence, compassion.",
            "Inner strength, self-doubt, low energy, raw emotion.",
            ["courage", "persuasion", "influence"],
            Tone::Positive,
            ctx("Gentle persistence wins where force fails.",
                "Patience and emotional steadiness deepen attraction.",
                "Build self-assurance first; genuine confidence is magnetic.",
                "Kindness and calm resolve help you navigate tension together.",
                "Handle pressure with grace. Your influence grows through trust.",
                "Resist pressure to spend; steady nerves protect wealth.",
                "Inner calm supports immunity and healing. Be patient with your body.")),
        major!(9, "The Hermit", "IX",
            "Soul searching, introspection, being alone, inner guidance.",
            "Isolation, loneliness, withdrawal, rejection.",
            ["introspection", "solitude", "guidance"],
            Tone::Neutral,
            ctx("Time alone provides clarity. Look inward for direction.",
                "A pause from dating may be wise while you figure out what you truly want.",
                "Solitude is healing; don’t force connection before you’re ready.",
                "Space can refresh the relationship, but communicate why to avoid hurt.",
                "Step back and reassess your path. Expert advice helps.",
                "Review finances alone. Cut unnecessary obligations.",
                "Rest, reflect, and seek professional guidance if symptoms persist.")),
        major!(10, "Wheel of Fortune", "X",
            "Good luck, karma, life cycles, destiny, a turning point.",
            "Bad luck, resistance to change, breaking cycles.",
            ["change", "cycles", "fate"],
            Tone::Neutral,
            ctx("Cycles turn. Adapt rather than resist.",
                "A fated meeting or sudden shift in your love life.",
                "Luck plays a role now; stay open to unexpected introductions.",
                "Fortune changes within the partnership; roll with it together.",
                "External forces shift opportunities. Stay flexible and ready.",
                "A financial turn—positive or negative—is temporary. Plan for both.",
                "Energy and health fluctuate; pace yourself through the cycle.")),
        major!(11, "Justice", "XI",
            "Justice, fairness, truth, cause and effect, law.",
            "Unfairness, lack of accountability, dishonesty.",
            ["justice", "fairness", "truth"],
            Tone::Neutral,
            ctx("Truth and fairness are required. Own your part.",
                "Honest conversations clarify where you stand with someone.",
                "Weigh what you truly need in a partner. Be fair to yourself too.",
                "Address imbalance directly. Accountability rebuilds trust.",
                "Contracts, negotiations, and honest assessments are favored.",
                "Balance the books and settle debts. Fair dealings pay off.",
                "Honest diagnosis and balanced habits support recovery.")),
        major!(12, "The Hanged Man", "XII",
            "Pause, surrender, letting go, new perspectives.",
            "Delays, resistance, stalling, indecision.",
            ["surrender", "new perspective", "pause"],
            Tone::Neutral,
            ctx("A pause before action. Letting go reveals the next step.",
                "A relationship may be on hold; use the wait to reflect.",
                "Don’t rush dating outcomes. Patience changes what you see.",
                "A sacrifice now may benefit the partnership later.",
                "Delay is information. Reconsider before pushing forward.",
                "Hold off on big purchases. Wait for clearer timing.",
                "Slow down. Rest and alternative therapies may help more than force.")),
        major!(13, "Death", "XIII",
            "Endings, change, transformation, transition.",
            "Resistance to change, inability to move on, stasis.",
            ["transformation", "endings", "change"],
            Tone::Negative,
            ctx("Necessary ending. Letting what no longer serves you fall away.",
                "A relationship chapter closes so a healthier one can begin.",
                "Release old patterns or crushes to make room for someone new.",
                "A transformation within the partnership—painful but needed.",
                "A role, project, or job is ending. Clear space for the new.",
                "A financial cycle ends. Rebuild with what remains.",
                "Release harmful habits. Recovery follows honest change.")),
        major!(14, "Temperance", "XIV",
            "Balance, moderation, patience, purpose, meaning.",
            "Imbalance, excess, self-healing, re-alignment.",
            ["balance", "moderation", "patience"],
            Tone::Neutral,
            ctx("Balance brings flow. Moderate effort outlasts extremes.",
                "A middle path in romance; avoid all-or-nothing thinking.",
                "Blend independence with openness. Don’t rush or withdraw.",
                "Cooperation and compromise renew harmony.",
                "Collaboration succeeds when everyone blends their strengths.",
                "Moderate spending and blend income streams for stability.",
                "Gentle, consistent self-care works better than drastic regimes.")),
        major!(15, "The Devil", "XV",
            "Shadow side, attachment, addiction, restriction, sexuality.",
            "Releasing limiting beliefs, exploring dark thoughts, detachment.",
            ["attachment", "addiction", "shadow"],
            Tone::Negative,
            ctx("Examine chains of habit or desire. Freedom is a choice.",
                "Toxic attraction or unhealthy patterns may be binding you.",
                "Don’t chase drama or unavailable people; break the pattern.",
                "Codependency or jealousy needs honest air. Reclaim individuality.",
                "A draining job or power dynamic. Break free or redefine terms.",
                "Overspending, debt, or scarcity mindset traps you. Face it.",
                "Addictions and compulsive behavior affect wellness. Seek support.")),
        major!(16, "The Tower", "XVI",
            "Sudden change, upheaval, chaos, revelation, awakening.",
            "Personal transformation, fear of change, averting disaster.",
            ["upheaval", "change", "revelation"],
            Tone::Negative,
            ctx("Sudden clarity disrupts old foundations. Rebuild on truth.",
                "A shock in love forces honesty. What crumbles needed to fall.",
                "Illusions about someone shatter. Better alone than deceived.",
                "A relationship crisis reveals what must change. Face it together.",
                "An unexpected shift at work. Adapt quickly and rebuild.",
                "Financial disruption—protect essentials and avoid panic moves.",
                "A health wake-up call. Address the root cause, not just symptoms.")),
        major!(17, "The Star", "XVII",
            "Hope, faith, purpose, renewal, spirituality.",
            "Lack of faith, despair, discouragement, insecurity.",
            ["hope", "faith", "renewal"],
            Tone::Positive,
            ctx("Hope is warranted. Pour energy into what renews you.",
                "Healing and optimism attract a gentler kind of love.",
                "Believe you are worthy of love; hope draws the right people.",
                "A quiet renewal of trust and intimacy after hardship.",
                "Inspiration returns. Creative or humanitarian work is favored.",
                "Long-term hopes become viable. Save and invest with vision.",
                "A hopeful sign for recovery. Gentle therapies and rest help.")),
        major!(18, "The Moon", "XVIII",
            "Illusion, fear, anxiety, subconscious, intuition.",
            "Release of fear, repressed emotion, inner confusion.",
            ["illusion", "fear", "intuition"],
            Tone::Neutral,
            ctx("Things are not as they seem. Trust intuition over surface appearances.",
                "Attraction may be fueled by fantasy. Seek clarity before commitment.",
                "Your imagination may idealize or fear dating. Slow down.",
                "Hidden feelings surface. Honesty dispels confusion.",
                "Office politics or unclear motives. Don’t act on incomplete info.",
                "Financial uncertainty. Avoid hidden risks and get advice.",
                "Anxiety may magnify symptoms. Ground yourself and seek facts.")),
        major!(19, "The Sun", "XIX",
            "Positivity, fun, warmth, success, vitality.",
            "Inner child, feeling down, overly optimistic, temporary depression.",
            ["positivity", "success", "vitality"],
            Tone::Positive,
            ctx("Joy and clarity shine. Success comes easily now.",
                "Radiant, warm connection. Be playful and open-hearted.",
                "Your authentic joy is magnetic. Enjoy meeting people.",
                "Happiness and mutual celebration brighten the relationship.",
                "Recognition, success, and confident energy at work.",
                "Financial warmth—bonuses, growth, or generous opportunities.",
                "Vitality is high. Sunshine and movement boost wellbeing.")),
        major!(20, "Judgement", "XX",
            "Judgement, rebirth, inner calling, absolution.",
            "Self-doubt, refusal of self-examination, ignoring the call.",
            ["rebirth", "inner calling", "absolution"],
            Tone::Neutral,
            ctx("A call to evolve. Answer it with self-honesty.",
                "A relationship decision based on who you’ve become.",
                "Reflect on past patterns before choosing your next connection.",
                "A second chance or deeper commitment after honest reckoning.",
                "A career calling or review. Step up to the next level.",
                "Evaluate money choices in light of long-term values.",
                "A turning point in health. Listen to your body’s message.")),
        major!(21, "The World", "XXI",
            "Completion, integration, accomplishment, travel.",
            "Seeking personal closure, short-cuts, delays.",
            ["completion", "integration", "accomplishment"],
            Tone::Positive,
            ctx("A cycle completes. Celebrate and integrate the lessons.",
                "A relationship reaches a fulfilling milestone.",
                "You’re whole on your own; this self-completion attracts healthy love.",
                "A sense of accomplishment together. Travel or shared joy is possible.",
                "Project or role completion. Recognition and new horizons.",
                "A financial chapter closes successfully. Plan the next.",
                "Integration of body and mind. Holistic wellness works.")),
    ]
}

fn minor_arcana() -> Vec<Card> {
    let suits = [Suit::Wands, Suit::Cups, Suit::Swords, Suit::Pentacles];
    let mut cards = Vec::with_capacity(56);
    for suit in suits {
        cards.extend(pips(&suit));
        cards.extend(court(&suit));
    }
    cards
}

fn pips(suit: &Suit) -> Vec<Card> {
    let suit_name = suit.to_string();
    let meanings = [
        (1, "Ace", "creation", "inspiration", "New beginnings in {s}. Creative spark, inspiration, will."),
        (2, "Two", "planning", "decisions", "Planning and decisions in {s}. Choices made, progress begins."),
        (3, "Three", "expansion", "growth", "Expansion and growth in {s}. Momentum, teamwork, initial results."),
        (4, "Four", "stability", "rest", "Stability and rest in {s}. Consolidation, sanctuary, grounding."),
        (5, "Five", "conflict", "loss", "Conflict and loss in {s}. Disruption, competition, setback."),
        (6, "Six", "harmony", "success", "Harmony and success in {s}. Restoration, generosity, victory."),
        (7, "Seven", "perseverance", "strategy", "Perseverance and strategy in {s}. Defense, patience, endurance."),
        (8, "Eight", "movement", "action", "Movement and action in {s}. Swift progress, focus, decisive energy."),
        (9, "Nine", "resilience", "completion", "Resilience and completion in {s}. Gratitude, fullness, sustained effort."),
        (10, "Ten", "culmination", "transition", "Culmination and transition in {s}. End of cycle, legacy, turning point."),
    ];

    meanings
        .iter()
        .map(|(num, label, kw1, kw2, tmpl)| {
            let theme = format!("{label} of {}", human_suit(suit));
            let image = format!("{suit_name}_pip_{num:02}");
            let upright = tmpl.replace("{s}", &human_suit(suit));
            let reversed = format!("Blocked or delayed energy of {theme}.");
            let ctxs = pip_contexts(*num, suit);
            Card {
                id: base_id_for_suit(suit) + num - 1,
                name: theme,
                arcana: Arcana::Minor,
                suit: *suit,
                number: Some(CardNumber(*num)),
                roman_numeral: None,
                upright_meaning: upright,
                reversed_meaning: reversed,
                keywords: vec![kw1.to_string(), kw2.to_string(), suit_name.clone()],
                image_ref: image,
                tone: pip_tone((*num).try_into().unwrap(), suit),
                contexts: ctxs,
            }
        })
        .collect()
}

fn court(suit: &Suit) -> Vec<Card> {
    let suit_name = suit.to_string();
    let courts = [
        ("Page", "Page of {}", "curiosity", "exploration", "Messenger of {s}. New approach, study, enthusiasm."),
        ("Knight", "Knight of {}", "action", "adventure", "Champion of {s}. Momentum, pursuit, daring."),
        ("Queen", "Queen of {}", "nurturing", "mastery", "Keeper of {s}. Mature energy, embodiment, care."),
        ("King", "King of {}", "authority", "leadership", "Ruler of {s}. Command, responsibility, mastery."),
    ];

    courts
        .iter()
        .enumerate()
        .map(|(idx, (_rank, fmt_name, kw1, kw2, tmpl))| {
            let base = base_id_for_suit(suit) + 10;
            let name = fmt_name.replace("{}", &human_suit(suit));
            let upright = tmpl.replace("{s}", &human_suit(suit));
            let reversed = format!("Overdone or withheld expression of {name}.");
            let rank = fmt_name.split_once(" of").map(|s| s.0).unwrap_or("Court");
            let ctxs = court_contexts(rank, suit);
            Card {
                id: base + idx as i32,
                name,
                arcana: Arcana::Minor,
                suit: *suit,
                number: None,
                roman_numeral: None,
                upright_meaning: upright,
                reversed_meaning: reversed,
                keywords: vec![kw1.to_string(), kw2.to_string(), suit_name.clone()],
                image_ref: format!("card_{:02}", base + idx as i32),
                tone: court_tone(suit, *kw1),
                contexts: ctxs,
            }
        })
        .collect()
}

fn base_id_for_suit(suit: &Suit) -> i32 {
    match suit {
        Suit::Wands => 22,
        Suit::Cups => 36,
        Suit::Swords => 50,
        Suit::Pentacles => 64,
        _ => 0,
    }
}

fn human_suit(suit: &Suit) -> String {
    match suit {
        Suit::Wands => "Wands".into(),
        Suit::Cups => "Cups".into(),
        Suit::Swords => "Swords".into(),
        Suit::Pentacles => "Pentacles".into(),
        Suit::None => "None".into(),
    }
}

fn ctx(
    general: &str,
    love_dating: &str,
    love_single: &str,
    love_relationship: &str,
    career: &str,
    money: &str,
    health: &str,
) -> ContextualMeanings {
    ContextualMeanings {
        general: general.into(),
        love_dating: love_dating.into(),
        love_single: love_single.into(),
        love_relationship: love_relationship.into(),
        career: career.into(),
        money: money.into(),
        health: health.into(),
    }
}

fn pip_contexts(num: i32, suit: &Suit) -> ContextualMeanings {
    match suit {
        Suit::Wands => match num {
            1 => ctx("A spark of passion or ambition. A new venture ignites.",
                "A bold, exciting attraction. Flirtation carries real heat.",
                "Your energy is magnetic now; take initiative toward someone who excites you.",
                "A surge of renewed passion. Try something new together.",
                "A new career opportunity demands courage. Seize the spark.",
                "A fresh income stream or investment idea. Act decisively.",
                "A burst of physical vitality. Start a new exercise or active habit."),
            2 => ctx("Planning your next move. Two paths forward.",
                "Choosing between suitors or approaches. Weigh chemistry and values.",
                "Decide what kind of partner you want before pursuing anyone.",
                "A decision about the future of the relationship. Align goals.",
                "Weigh two offers or strategies carefully before committing.",
                "A choice between spending and saving. Plan before acting.",
                "Balance two health priorities. Avoid extremes."),
            3 => ctx("Momentum builds. Initial results appear.",
                "A connection is growing. Enjoy the early momentum.",
                "Social expansion brings romantic possibilities.",
                "Plans together start to take shape. Celebrate small wins.",
                "Teamwork pays off. A project gains traction.",
                "Small gains add up. Keep building consistently.",
                "Early progress in a fitness or recovery plan. Stay consistent."),
            4 => ctx("Consolidation. Celebrate progress before the next push.",
                "Stability in romance. A comfortable, steady phase.",
                "Enjoy your own company; secure singles attract solid partners.",
                "A milestone worth celebrating. Build traditions together.",
                "A stable position. Use this base to plan growth.",
                "Financial security improves. Consolidate gains.",
                "Recovery and strength. Rest allows progress to hold."),
            5 => ctx("Conflict and competition. Strain tests your resolve.",
                "Arguments or rivalry. Avoid ego battles.",
                "Dating feels competitive or discouraging. Don’t compare yourself.",
                "A disagreement challenges the bond. Fair conflict can clear the air.",
                "Workplace friction or competition. Hold your ground calmly.",
                "Unexpected expenses or financial rivalry. Protect essentials.",
                "Stress depletes energy. Manage conflict to protect wellbeing."),
            6 => ctx("Victory and recognition after effort.",
                "A romantic win. Mutual admiration and pride.",
                "Self-confidence leads to a welcome connection.",
                "A shared triumph. Support each other publicly.",
                "Success and acknowledgment in your role.",
                "A financial victory or reward. Share generously.",
                "A breakthrough in energy or healing. Momentum returns."),
            7 => ctx("Defensive position. Persevere and reassess strategy.",
                "You may feel guarded in love. Patience protects you.",
                "Be selective. Not every interest deserves your energy.",
                "External pressures test you. Stand together without closing off.",
                "Defend your position, but avoid unnecessary battles.",
                "Protect your budget. Watch for leaks and delayed payments.",
                "Defensive fatigue. Support immunity with rest and boundaries."),
            8 => ctx("Rapid movement. Swift action toward a clear goal.",
                "A fast-developing attraction. Move with clarity, not haste.",
                "Quick progress if you put yourself out there actively.",
                "A dynamic phase. Plans accelerate together.",
                "Things move fast professionally. Keep focused.",
                "Money moves quickly—earnings or spending. Track it closely.",
                "Energy flows well. Sustain the pace without burnout."),
            9 => ctx("Resilience and readiness. Stand your ground.",
                "A tested but enduring connection. Loyalty matters most.",
                "Your independence is your strength. Keep standards high.",
                "Weather a challenge together. Patience wins.",
                "Proven reliability earns trust and advancement.",
                "Your reserves hold. Avoid unnecessary risk.",
                "Stamina and recovery are strong. Persist with care."),
            10 => ctx("Burden of responsibility. Delegate or finish the cycle.",
                "Obligations weigh on romance. Share the load.",
                "Dating may feel like pressure. Release self-imposed deadlines.",
                "Shared responsibilities need fair division. Talk it through.",
                "Heavy workload. Finish what you started before taking more.",
                "Financial pressure peaks. Address debt or obligations honestly.",
                "Carrying stress in the body. Release tension through movement."),
            _ => ContextualMeanings::default(),
        },
        Suit::Cups => match num {
            1 => ctx("A new emotional beginning. Love, joy, or intuition overflows.",
                "A deep new feeling emerges. Be open to emotional intimacy.",
                "A new crush or emotional renewal. Welcome love in.",
                "A fresh wave of love and tenderness. Deepen emotional connection.",
                "Creative inspiration or emotional fulfillment from work.",
                "Emotional satisfaction with money. Gratitude attracts abundance.",
                "Emotional wellbeing boosts physical health. Joy heals."),
            2 => ctx("Union and mutual attraction. Two hearts in balance.",
                "A promising pairing. Mutual interest is strong.",
                "A meaningful meeting is possible. Be receptive.",
                "Harmony and attraction. A soulmate-type bond strengthens.",
                "A strong partnership or collaboration. Trust grows.",
                "A balanced financial partnership. Shared values help.",
                "Body-mind harmony. Gentle connection supports healing."),
            3 => ctx("Friendship, celebration, community.",
                "Social fun may lead to romance. Group settings help.",
                "Enjoy friends; love may grow from shared joy.",
                "Celebrate with friends together. Social joy renews love.",
                "Team morale and creative collaboration flourish.",
                "Reward yourself modestly, but avoid group-pressure spending.",
                "Social support aids recovery. Laugh with people you trust."),
            4 => ctx("Emotional stability and quiet contentment.",
                "A calm, loving phase. Don’t disrupt it searching for drama.",
                "Find contentment within; it attracts healthier love.",
                "A peaceful period together. Appreciate simple affection.",
                "Satisfaction in work. Steady progress is enough.",
                "Financial contentment. Avoid restless spending.",
                "Emotional calm supports the body. Rest and recharge."),
            5 => ctx("Loss or disappointment. Grief needs space to pass.",
                "A letdown in love. Allow yourself to mourn without rushing.",
                "Disappointment may close you off. Healing comes first.",
                "A painful gap or rejection. Talk honestly or seek support.",
                "A setback or missed opportunity. Process it before moving on.",
                "A financial loss. Rebuild slowly and realistically.",
                "Emotional grief can affect the body. Sleep, hydrate, seek care."),
            6 => ctx("Nostalgia and childhood memory. Innocent joy returns.",
                "Sweet, innocent affection. Old flames or familiar comfort.",
                "Kindness and nostalgia may bring someone closer.",
                "Revisit happy memories. Playful tenderness rekindles love.",
                "Past skills or mentors help current progress.",
                "A gift or return on a past effort. Appreciate it.",
                "Childlike joy and gentle play support wellbeing."),
            7 => ctx("Fantasy and options. Dreams need reality testing.",
                "Many possibilities but unclear motives. Take your time.",
                "Don’t get lost in fantasies about someone you barely know.",
                "Wishful thinking may cloud a real issue. Be honest.",
                "Too many choices. Prioritize and commit to one path.",
                "Illusions about a deal or windfall. Verify before spending.",
                "Anxiety fed by imagination. Ground yourself with facts."),
            8 => ctx("Walking away from emotional drain. A necessary departure.",
                "A relationship no longer fulfills you. Leaving may be right.",
                "Release a dead-end crush. Better awaits.",
                "A separation or emotional retreat. Clarity comes with distance.",
                "Move on from a role that drains you. Growth requires change.",
                "Cut losses on a bad investment or spending habit.",
                "Release a habit that harms your body. Recovery follows."),
            9 => ctx("Emotional fulfillment and wish come true.",
                "A dream relationship manifests. Savor the connection.",
                "Your hopes in love are realized. Stay open.",
                "Deep satisfaction together. A wish shared between you.",
                "A dream role or project comes to fruition.",
                "Financial wishes edge closer. Receive with gratitude.",
                "Emotional wellness overflows into physical vitality."),
            10 => ctx("Emotional completion and family harmony.",
                "A relationship reaches wholeness. Family and love align.",
                "You feel complete; this attracts the right partner.",
                "A happy home life. Emotional security together.",
                "A fulfilling career chapter. Work feels like family.",
                "Domestic and financial harmony. Long-term security.",
                "Whole-body wellness. Family support aids recovery."),
            _ => ContextualMeanings::default(),
        },
        Suit::Swords => match num {
            1 => ctx("A breakthrough idea or mental clarity. The truth cuts through.",
                "A moment of clarity about someone. Speak honestly.",
                "Clear intentions attract the right connection. Be direct.",
                "An honest conversation clears the air. Use kindness with truth.",
                "A breakthrough concept. Act on it decisively.",
                "A clear-headed money decision. Cut confusion.",
                "Mental clarity aids diagnosis and treatment."),
            2 => ctx("Indecision. Avoidance keeps you stuck.",
                "You’re torn between feelings. Avoidance worsens it.",
                "Weigh what you want, then act. Don’t wait forever.",
                "A difficult choice in the relationship. Face it together.",
                "A hard decision looms. Gather facts and commit.",
                "Avoid financial denial. Look at the numbers honestly.",
                "Ignoring symptoms prolongs illness. Seek clarity."),
            3 => ctx("Heartbreak and sorrow. Pain precedes healing.",
                "A painful romantic loss. Give yourself time.",
                "Old heartache may resurface. Process it to move forward.",
                "Grief or betrayal in the partnership. Support and honesty help.",
                "A professional disappointment. Allow yourself to recover.",
                "A financial hit. Protect essentials and rebuild.",
                "Emotional stress manifests physically. Rest and heal."),
            4 => ctx("Rest and recovery after mental battle.",
                "A pause from conflict. Use it to restore trust.",
                "Solitude helps you recover from dating stress.",
                "A quiet retreat together prevents burnout.",
                "Step back from a stressful project. Recovery restores judgement.",
                "Avoid money stress temporarily. Regroup before deciding.",
                "Convalescence and gentle care. Sleep and reset."),
            5 => ctx("Conflict and hollow victory. Arguments cost more than they win.",
                "A fight where winning means losing closeness. Choose peace.",
                "Don’t compromise your values just to win attention.",
                "A dispute threatens the bond. Apologize or disengage.",
                "Office conflict. Winning battles may lose allies.",
                "A financial dispute. Legal or personal costs loom.",
                "Conflict stresses the nervous system. Calm the mind."),
            6 => ctx("Transition after difficulty. Moving toward calmer waters.",
                "Healing from a rough patch. Better dynamics ahead.",
                "You’re moving on from a disappointing situation.",
                "A shared recovery. Leave the worst behind together.",
                "Leaving a toxic situation. Relief follows.",
                "Financial recovery begins. Stay cautious.",
                "Convalescence leads to improvement. Cross the threshold."),
            7 => ctx("Deception or strategy. Trust but verify.",
                "Hidden agendas or game-playing. Watch for red flags.",
                "Someone may not be showing their true self. Proceed slowly.",
                "Secrecy or sneakiness damages trust. Address it directly.",
                "Office politics or hidden motives. Protect your interests.",
                "Beware scams or hidden fees. Verify everything.",
                "Stress from uncertainty affects sleep. Seek facts."),
            8 => ctx("Mental entrapment. Negative thoughts loop until you break free.",
                "Feeling trapped by anxiety or obsession. Seek perspective.",
                "Fear of rejection keeps you stuck. Take a small risk.",
                "A restrictive dynamic. Open conversation creates escape.",
                "You feel stuck professionally. Identify one small exit step.",
                "Financial anxiety paralyzes you. A small action breaks the loop.",
                "Anxiety affects the body. Grounding and breathing help."),
            9 => ctx("Nightmares and worry. Anxiety magnifies problems.",
                "Love worries keep you awake. Most fears are projections.",
                "Anxiety about being alone is amplified now. Reach out to friends.",
                "Shared worry creates distance. Reassure each other with facts.",
                "Projecting worst-case scenarios harms judgement. Get data.",
                "Money anxiety is worse than the reality. Review numbers calmly.",
                "Insomnia and tension need attention. Reduce stimulants and rest."),
            10 => ctx("End of a painful mental cycle. Rock bottom becomes foundation.",
                "A painful ending. From here, things can only improve.",
                "Release an exhausting romantic hope. End the cycle.",
                "A low point, but shared honesty can rebuild.",
                "A project or role ends painfully. Learn and rise.",
                "A financial low. Face it and plan recovery.",
                "Mental and physical exhaustion. Rest is non-negotiable."),
            _ => ContextualMeanings::default(),
        },
        Suit::Pentacles => match num {
            1 => ctx("A tangible new opportunity rooted in reality.",
                "A solid, grounded attraction. Build something real.",
                "A practical new start. Focus on stability, not drama.",
                "A gift or blessing for the relationship. Material security begins.",
                "A promising opportunity with real potential. Invest effort.",
                "A new income source or investment seed. Nurture it.",
                "A new wellness foundation offers lasting results."),
            2 => ctx("Juggling priorities. Balance is essential.",
                "Balancing love with other responsibilities. Be present.",
                "You have options but limited time. Choose quality over quantity.",
                "Shared duties require fair sharing. Avoid over-functioning.",
                "Multiple tasks demand balance. Prioritize well.",
                "Balancing income and outgo. Stay flexible.",
                "Balance work and body care. Don’t neglect rest."),
            3 => ctx("Teamwork and skilled craft. Collaboration builds success.",
                "A relationship grows through shared effort and patience.",
                "Community or hobby groups may introduce a match.",
                "Working together on projects deepens appreciation.",
                "Skill and cooperation lead to advancement.",
                "Teamwork improves finances. Practical planning works.",
                "A structured health routine pays off."),
            4 => ctx("Holding on tightly. Security can become stagnation.",
                "Guardedness may block intimacy. Loosen your grip.",
                "Don't let fear of loss prevent connection.",
                "A possessive phase. Share more freely to deepen trust.",
                "Hoarding resources or credit stifles growth. Distribute wisely.",
                "Holding money too tightly blocks abundance. Invest smartly.",
                "Stiffness or rigidity in the body. Stretch and release."),
            5 => ctx("Material hardship or exclusion. Lean on community.",
                "Financial or social strain affects romance. Be honest.",
                "Feeling left out? Reach out rather than isolate.",
                "A hard season tests the relationship. Support each other.",
                "Job loss or resource scarcity. Seek help and options.",
                "A lean financial period. Cut waste and ask for support.",
                "Economic stress affects health. Use available resources."),
            6 => ctx("Generosity and fair exchange. Give and receive.",
                "Kindness and generosity strengthen love.",
                "Be open to both giving and receiving affection.",
                "A balanced exchange of care. Small gifts matter.",
                "Mentoring or sharing resources advances your career.",
                "Charity and smart giving improve your financial flow.",
                "Generosity to your body—good food, rest, care."),
            7 => ctx("Patience and long-term growth. Wait and tend.",
                "A relationship needs time to mature. Don’t force it.",
                "Slow down your search. The right connection grows naturally.",
                "Tend the partnership daily. Small efforts compound.",
                "Long-term rewards come from steady effort now.",
                "A slow-growing investment is better than a quick gamble.",
                "Healing takes time. Be patient with your body."),
            8 => ctx("Diligence and mastery. Hard work refines skill.",
                "Consistent effort and attention build a lasting bond.",
                "Becoming your best self attracts better partners.",
                "Daily acts of care accumulate into deep trust.",
                "Apprenticeship and disciplined effort pay off.",
                "Steady saving and skill-building increase wealth.",
                "Consistent healthy habits build strength."),
            9 => ctx("Comfort and discipline. Abundance earned through care.",
                "A secure, loving partnership where needs are met.",
                "Self-care makes you a strong partner. Enjoy your own company.",
                "A stable, abundant home life together.",
                "A secure position earned through competence.",
                "Financial comfort. Protect and enjoy what you’ve built.",
                "Strong health through consistent self-discipline."),
            10 => ctx("Legacy and family wealth. Long-term security.",
                "A relationship grounded in family, home, and legacy.",
                "Build a life you love; the right partner fits into it.",
                "Family and home life flourish. A solid inheritance of love.",
                "Career legacy comes into focus. Mentor the next generation.",
                "Wealth, property, or inheritance matters. Plan long term.",
                "Family health and habits shape wellbeing across generations."),
            _ => ContextualMeanings::default(),
        },
        _ => ContextualMeanings::default(),
    }
}

fn court_contexts(rank: &str, suit: &Suit) -> ContextualMeanings {
    let s = human_suit(suit);
    match (rank, suit) {
        ("Page", Suit::Wands) => ctx("Messenger of passion and ideas. A new spark arrives.",
            "A bold, youthful admirer or exciting invitation.",
            "A fun, energetic introduction may lead somewhere.",
            "A playful new energy enters the relationship—try it.",
            "A new opportunity, offer, or enthusiastic apprentice.",
            "A fresh idea for earning or spending creatively.",
            "A burst of youthful energy; start a new active hobby."),
        ("Page", Suit::Cups) => ctx("Messenger of emotion. A sweet message or creative offer.",
            "A tender confession or affectionate note.",
            "Someone may quietly express interest. Stay open.",
            "A loving gesture renews sweetness.",
            "Creative proposal or kind feedback at work.",
            "A small but meaningful money gift or opportunity.",
            "Emotional openness supports healing."),
        ("Page", Suit::Swords) => ctx("Messenger of ideas or criticism. Curiosity needs tact.",
            "A curious but possibly blunt communication.",
            "Intellectual banter sparks a connection. Don’t overthink.",
            "Honest words may feel sharp but clear the air.",
            "A new idea or critique. Listen and learn.",
            "A question about finances needs a clear answer.",
            "Curiosity about symptoms leads to useful research."),
        ("Page", Suit::Pentacles) => ctx("Messenger of practical opportunity. A tangible offer.",
            "A steady, reliable person shows interest.",
            "A practical new chance. Focus on real compatibility.",
            "A helpful offer or material support in the relationship.",
            "An entry-level opportunity with real growth potential.",
            "A practical money idea or scholarship. Take it seriously.",
            "A small but steady health improvement begins."),
        ("Knight", Suit::Wands) => ctx("Passionate, fast-moving energy. Adventure calls.",
            "A whirlwind romance or bold pursuit.",
            "An exciting but possibly impulsive suitor appears.",
            "A passionate push forward together. Keep communication open.",
            "Aggressive career momentum. Channel energy strategically.",
            "Fast money movement. Profit or loss can happen quickly.",
            "High physical energy. Use it, then rest."),
        ("Knight", Suit::Cups) => ctx("Romantic offer or invitation. Follow the heart.",
            "A heartfelt proposal or romantic gesture.",
            "Someone approaches with genuine feeling. Consider it.",
            "A partner offers deeper emotional commitment.",
            "A creative or compassionate opportunity at work.",
            "An emotionally appealing offer. Verify the fine print.",
            "Emotional expression eases stress."),
        ("Knight", Suit::Swords) => ctx("Rapid, decisive action. Think before charging.",
            "A rushed romantic move. Slow down if it feels forced.",
            "Directness is attractive, but aggression is not.",
            "A push to resolve something quickly. Breathe first.",
            "Swift professional action. Prepare before leaping.",
            "A fast financial decision. Read details carefully.",
            "Stress-driven energy. Calm the mind before acting."),
        ("Knight", Suit::Pentacles) => ctx("Steady, methodical progress. Slow and reliable.",
            "A slow-burn, dependable attraction.",
            "Someone serious and consistent may enter your life.",
            "A dependable partner delivering on promises.",
            "Reliable advancement through diligence.",
            "Steady financial growth. Patience pays.",
            "Consistent habits restore health."),
        ("Queen", Suit::Wands) => ctx("Confident, magnetic leadership. Authenticity attracts.",
            "A passionate, self-assured presence lights up romance.",
            "Your confidence is your superpower. Own it.",
            "Lead the relationship with warmth and independence.",
            "Leadership through vision and charisma. Inspire others.",
            "Invest with confidence. Your instincts are sharp.",
            "Vitality and self-assurance support wellbeing."),
        ("Queen", Suit::Cups) => ctx("Deep emotional intuition and nurturing love.",
            "A deeply caring connection. Trust your heart.",
            "Self-compassion makes you ready for real love.",
            "Nurturing and intuitive care strengthen the bond.",
            "Emotional intelligence makes you invaluable at work.",
            "Generosity improves your financial flow.",
            "Listen to your body’s subtle signals."),
        ("Queen", Suit::Swords) => ctx("Clear boundaries and honest discernment.",
            "Set firm standards in love. Honesty clears confusion.",
            "Don't lower standards out of loneliness.",
            "Direct communication with compassion protects the relationship.",
            "Sharp judgment and integrity earn respect.",
            "Cut unnecessary expenses with clear logic.",
            "Mental clarity supports recovery."),
        ("Queen", Suit::Pentacles) => ctx("Practical nurturing and grounded abundance.",
            "A warm, stable partner who creates comfort.",
            "Build a life that feels safe and abundant on your own.",
            "Care for home, health, and each other together.",
            "A reliable, resourceful professional. Practical success.",
            "Wise management of money and resources.",
            "Nourishment and routine restore the body."),
        ("King", Suit::Wands) => ctx("Visionary leadership and bold mastery.",
            "A charismatic leader in love. Inspire and protect.",
            "Attract by pursuing your passions with boldness.",
            "A strong, protective energy. Lead with integrity.",
            "Executive vision and entrepreneurial fire.",
            "Bold financial leadership. Take calculated risks.",
            "Strong vitality through purposeful action."),
        ("King", Suit::Cups) => ctx("Emotional maturity and compassionate authority.",
            "A steady, loving partner. Emotional safety deepens love.",
            "Mature love comes when you master your own emotions.",
            "Lead the relationship with calm empathy.",
            "Wise leadership through emotional intelligence.",
            "Generous but disciplined use of wealth.",
            "Emotional balance anchors physical health."),
        ("King", Suit::Swords) => ctx("Intellectual authority and decisive truth.",
            "Honest standards attract the right partner.",
            "Clear boundaries and self-respect draw respect.",
            "A fair but firm decision shapes the future.",
            "Strategic authority and rational leadership.",
            "Cold, hard financial logic wins. Make the tough call.",
            "A clinical, disciplined approach to health."),
        ("King", Suit::Pentacles) => ctx("Master of material security and long-term legacy.",
            "A stable, prosperous partner. Security is romantic.",
            "Build your own kingdom; the right person respects it.",
            "A secure, abundant home life together.",
            "Top of your field through discipline and results.",
            "Wealth management and legacy planning.",
            "Long-term physical wellbeing through disciplined routine."),
        _ => ctx(&format!("The essence of {rank} of {s}."),
            &format!("{rank} of {s} influences your love life."),
            &format!("{rank} of {s} guides your single journey."),
            &format!("{rank} of {s} shapes your relationship."),
            &format!("{rank} of {s} affects your career."),
            &format!("{rank} of {s} influences your finances."),
            &format!("{rank} of {s} relates to your health.")),
    }
}

fn pip_tone(num: usize, suit: &Suit) -> Tone {
    match suit {
        Suit::Wands => match num {
            5 | 10 => Tone::Negative,
            1 | 6 | 8 => Tone::Positive,
            _ => Tone::Neutral,
        },
        Suit::Cups => match num {
            5 => Tone::Negative,
            1 | 2 | 3 | 6 | 9 | 10 => Tone::Positive,
            _ => Tone::Neutral,
        },
        Suit::Swords => match num {
            3 | 5 | 7 | 9 | 10 => Tone::Negative,
            _ => Tone::Neutral,
        },
        Suit::Pentacles => match num {
            5 => Tone::Negative,
            1 | 9 | 10 => Tone::Positive,
            _ => Tone::Neutral,
        },
        _ => Tone::Neutral,
    }
}

fn court_tone(suit: &Suit, kw1: &str) -> Tone {
    match (suit, kw1) {
        (Suit::Cups, _) => Tone::Positive,
        (Suit::Wands, "action") | (Suit::Wands, "adventure") => Tone::Positive,
        (Suit::Swords, _) => Tone::Neutral,
        (Suit::Pentacles, "authority") | (Suit::Pentacles, "leadership") => Tone::Neutral,
        _ => Tone::Neutral,
    }
}
