use crate::models::{Entity, EntityType, Tone};

pub fn build_entities() -> Vec<Entity> {
    vec![
        Entity {
            id: 0,
            name: "Residual Haunt".into(),
            entity_type: EntityType::Ghost,
            origin: "Common paranormal model; imprint theory from psychical research and folklore.".into(),
            description: "An imprint left behind by intense emotion or trauma. Replays like a recording, usually unaware of the living.".into(),
            signs: vec!["repeating sounds or voices".into(), "footsteps on the same stair".into(), "figures seen in the same place".into()],
            weaknesses: vec!["typically fades once the imprinted energy dissipates".into(), "ignoring it starves the loop".into(), "salt lines block the path it repeats".into()],
            banishment: "Usually requires no banishment; lay salt, remove emotional triggers, and let the imprint fade over time.".into(),
            tone: Tone::Neutral,
            danger: "Minimal — rarely interacts.".into(),
            is_custom: false.into(),
        },
        Entity {
            id: 1,
            name: "Shadow Person".into(),
            entity_type: EntityType::Shade,
            origin: "Modern paranormal accounts; linked to sleep paralysis and liminal-space phenomena.".into(),
            description: "A dark humanoid silhouette observed at the edge of vision. Often associated with sleep paralysis, stress, or liminal spaces.".into(),
            signs: vec!["black figure at the bedroom door".into(), "watching from corners".into(), "sudden drop in temperature".into(), "overwhelming dread".into()],
            weaknesses: vec!["bright light and exposure".into(), "firm boundaries and refusal of fear".into(), "cleaning cluttered or stagnant spaces".into()],
            banishment: "Turn on lights, speak its presence away, cleanse with frankincense or camphor, and sleep with a lit candle nearby.".into(),
            tone: Tone::Neutral,
            danger: "Low to moderate — fear feeds them.".into(),
            is_custom: false.into(),
        },
        Entity {
            id: 2,
            name: "Poltergeist".into(),
            entity_type: EntityType::Poltergeist,
            origin: "German folklore ('noisy ghost'); often tied to living agent distress in parapsychology.".into(),
            description: "A noisy spirit that moves objects, slams doors, and causes disturbances. Often linked to emotional distress in adolescents or the home.".into(),
            signs: vec!["objects thrown or displaced".into(), "loud knocking or banging".into(), "electronics acting up".into(), "fires or scratches".into()],
            weaknesses: vec!["calming the household".into(), "removing stress triggers".into(), "iron and salt barriers".into()],
            banishment: "Restore peace in the home, perform a house blessing with salt water and iron, and remove the targeted person from tension.".into(),
            tone: Tone::Negative,
            danger: "Moderate — can be physically violent.".into(),
            is_custom: false.into(),
        },
        Entity {
            id: 3,
            name: "Intelligent Spirit".into(),
            entity_type: EntityType::Spirit,
            origin: "Spiritualist and global ancestor-tradition model of conscious dead.".into(),
            description: "A conscious, self-aware deceased presence that can respond to questions or people.".into(),
            signs: vec!["answers questions through knocks or lights".into(), "responds to names".into(), "appears in dreams".into(), "moves meaningful objects".into()],
            weaknesses: vec!["respectful but firm communication".into(), "boundaries about acceptable behaviour".into()],
            banishment: "Open a dialogue, ask what it wants, then politely but firmly command it to rest; close with a clearing prayer.".into(),
            tone: Tone::Neutral,
            danger: "Usually low — may be protective or seeking help.".into(),
            is_custom: false.into(),
        },
        Entity {
            id: 4,
            name: "Banshee".into(),
            entity_type: EntityType::Spirit,
            origin: "Irish and Scottish folklore; bean sídhe, fairy woman of the mounds.".into(),
            description: "A wailing spirit that foretells death or disaster. Often appears near family bloodlines.".into(),
            signs: vec!["mournful wailing at night".into(), "apparition of an old woman".into(), "sensation of grief before bad news".into()],
            weaknesses: vec!["cannot be banished, only heeded".into(), "protective charms ease the warning".into()],
            banishment: "Do not banish; honour the warning, wear a protective charm, and tend to the family's health and safety.".into(),
            tone: Tone::Neutral,
            danger: "Omen — not inherently hostile.".into(),
            is_custom: false.into(),
        },
        Entity {
            id: 5,
            name: "Demonic Oppressor".into(),
            entity_type: EntityType::Demon,
            origin: "Abrahamic demonology and worldwide religious traditions of hostile spirits.".into(),
            description: "A malevolent entity that feeds on fear, suffering, and submission. Often pretends to be a dead loved one at first.".into(),
            signs: vec!["heavy, suffocating presence".into(), "religious items disturbed".into(), "scratches in threes".into(), "foul sulphur smell".into(), "mocking or blasphemous voices".into()],
            weaknesses: vec!["holy names and prayers".into(), "exorcism or banishment rite".into(), "salt, iron, and blessed water".into(), "refusing to engage mentally".into()],
            banishment: "Use faith-based authority, salt and iron barriers, and a structured banishment rite; seek experienced help if it escalates.".into(),
            tone: Tone::Negative,
            danger: "High — seek experienced help.".into(),
            is_custom: false.into(),
        },
        Entity {
            id: 6,
            name: "Wrath Demon".into(),
            entity_type: EntityType::Demon,
            origin: "Infernal tradition; personifications of anger and vengeance across cultures.".into(),
            description: "A violent demonic force drawn to anger, resentment, and vengeful thoughts.".into(),
            signs: vec!["unexplained fires".into(), "aggressive shadow attacks".into(), "people lashing out uncharacteristically".into()],
            weaknesses: vec!["peace offerings and forgiveness rituals".into(), "cooling emotional conflicts".into(), "binding sigils".into()],
            banishment: "Calm all conflicts in the space, perform a binding with a written command under a black candle, and scatter blessed salt at thresholds.".into(),
            tone: Tone::Negative,
            danger: "High — targets aggression.".into(),
            is_custom: false.into(),
        },
        Entity {
            id: 7,
            name: "Fae Trickster".into(),
            entity_type: EntityType::Fae,
            origin: "Celtic and Northern European fairy folklore.".into(),
            description: "A mischievous fairy or fae being that loves bargains, tricks, and stolen valuables. Never accept gifts freely.".into(),
            signs: vec!["objects vanish and reappear".into(), "hearing bells or laughter outdoors".into(), "circles of mushrooms or stones".into(), "bargain-like coincidences".into()],
            weaknesses: vec!["cold iron".into(), "refusing gifts and bargains".into(), "salt and rowan wood".into(), "speaking plain truth".into()],
            banishment: "Place iron and rowan above the door, speak plainly and refuse bargains, and leave a small offering of milk or bread outside to buy peace.".into(),
            tone: Tone::Neutral,
            danger: "Moderate — annoyance and bad luck more than physical harm.".into(),
            is_custom: false.into(),
        },
        Entity {
            id: 8,
            name: "Unseelie Courtier".into(),
            entity_type: EntityType::Fae,
            origin: "Scottish fairy courts; the Unseelie Court of dark fae nobility.".into(),
            description: "A noble fae from the darker court. Beautiful, dangerous, and bound by oaths and etiquette.".into(),
            signs: vec!["ethereal beauty in the woods at dusk".into(), "offers too good to be true".into(), "time moving strangely".into()],
            weaknesses: vec!["exact wording of agreements".into(), "iron".into(), "refusal to enter bargains".into()],
            banishment: "Carry iron, avoid oaths, and if bound, use the precise wording of any agreement to break it; ring bells to drive them off.".into(),
            tone: Tone::Negative,
            danger: "High — can bind or enthrall.".into(),
            is_custom: false.into(),
        },
        Entity {
            id: 9,
            name: "Wraith".into(),
            entity_type: EntityType::Wraith,
            origin: "Scottish usage and modern fantasy; anguished undead tied to unfinished obsession.".into(),
            description: "A tormented soul kept from rest by obsession, revenge, or unfinished business. Drains warmth and life.".into(),
            signs: vec!["freezing cold spots".into(), "whispered names".into(), "feeling of being watched from behind".into(), "plants withering nearby".into()],
            weaknesses: vec!["resolving the unfinished grievance".into(), "drying herbs like rosemary or sage".into(), "spiritual cleansing of the place".into()],
            banishment: "Discover and address the unmet need, burn rosemary and sage, and speak a release command while facing north at midnight.".into(),
            tone: Tone::Negative,
            danger: "Moderate to high — can drain vitality.".into(),
            is_custom: false.into(),
        },
        Entity {
            id: 10,
            name: "Fetch".into(),
            entity_type: EntityType::Spirit,
            origin: "Irish folklore; a spectral double or fetch that foreshadows death.".into(),
            description: "A spectral double of a living person that appears as an omen of death or great change.".into(),
            signs: vec!["seeing yourself from outside".into(), "doppelgänger wearing grey or pale clothes".into(), "news of illness follows".into()],
            weaknesses: vec!["avoid acknowledging it directly".into(), "protective ancestral rites".into()],
            banishment: "Do not greet it; perform ancestral protection rites, wear a token tied to family luck, and prepare spiritually for change.".into(),
            tone: Tone::Neutral,
            danger: "Omen — prepare for loss or transformation.".into(),
            is_custom: false.into(),
        },
        Entity {
            id: 11,
            name: "Revenant".into(),
            entity_type: EntityType::Ghost,
            origin: "Medieval European folklore; returned corpses or spirits with unfinished purpose.".into(),
            description: "A corpse or spirit returned with purpose, often to settle a wrong or deliver a message.".into(),
            signs: vec!["knocking at the door or window".into(), "disturbed graves or heirlooms".into(), "dream visits asking for something".into()],
            weaknesses: vec!["fulfilling the request or righting the wrong".into(), "salt on the threshold".into()],
            banishment: "Discover what it wants, provide the requested justice or message, then lay salt across thresholds and bid it rest.".into(),
            tone: Tone::Neutral,
            danger: "Moderate — can become violent if ignored.".into(),
            is_custom: false.into(),
        },
        // Angels
        Entity {
            id: 100,
            name: "Guardian Angel".into(),
            entity_type: EntityType::Angel,
            origin: "Common across Jewish, Christian, and Islamic folk belief; tutelary spirits assigned to a person.".into(),
            description: "A benevolent watcher that steers its charge away from harm, nudges intuition, and brings comfort in crisis.".into(),
            signs: vec!["sudden warmth or chill of peace".into(), "feathers appearing unexpectedly".into(), "a voice or name called just before danger".into(), "dreams of a familiar stranger".into()],
            weaknesses: vec!["can only guide, not override free will".into(), "strong doubt or fear can muffle its presence".into()],
            banishment: "Never banish; speak a prayer of thanks, light a white candle, and simply ask for space when overwhelmed.".into(),
            tone: Tone::Positive,
            danger: "None — protective and gentle.".into(),
            is_custom: false.into(),
        },
        Entity {
            id: 101,
            name: "Messenger Angel".into(),
            entity_type: EntityType::Angel,
            origin: "Abrahamic and esoteric traditions; couriers between the divine and the mortal.".into(),
            description: "A swift herald bearing signs, dreams, numbers, or words repeated until they are understood.".into(),
            signs: vec!["repeating numbers, words, or songs".into(), "visions of wings or bright eyes".into(), "a single phrase looping in the mind".into(), "light flickers during questions".into()],
            weaknesses: vec!["must be heard, not forced".into(), "ignoring the message makes the sign stronger".into()],
            banishment: "Do not banish; write the message down, meditate on it, and acknowledge receipt.".into(),
            tone: Tone::Positive,
            danger: "None — may be intense but never harmful.".into(),
            is_custom: false.into(),
        },
        Entity {
            id: 102,
            name: "Avenging Angel".into(),
            entity_type: EntityType::Angel,
            origin: "Abrahamic folklore; agents of wrath who punish the wicked and defend the wronged.".into(),
            description: "A fierce protective angel that confronts predators, tyrants, and those who harm the innocent.".into(),
            signs: vec!["a sudden reckoning for cruelty".into(), "accidents befalling an oppressor".into(), "dreams of fire and a sword of light".into(), "unshakeable sense of justice".into()],
            weaknesses: vec!["respect for truth; cannot harm the innocent".into(), "prayers for mercy can soften its edge".into()],
            banishment: "Not banished; instead, make amends and ask forgiveness before the scales fall.".into(),
            tone: Tone::Positive,
            danger: "High for the guilty — none for the innocent.".into(),
            is_custom: false.into(),
        },
        Entity {
            id: 103,
            name: "Healing Angel".into(),
            entity_type: EntityType::Angel,
            origin: "Mystical and folk medicine traditions; radiance that mends illness, grief, and exhaustion.".into(),
            description: "A soft, warm presence that eases pain, calms panic, and helps the body remember how to heal.".into(),
            signs: vec!["a glowing figure at the bedside".into(), "pain suddenly diminishing".into(), "scent of roses, frankincense, or honey".into(), "deep restful sleep after long insomnia".into()],
            weaknesses: vec!["works best with medical care and rest".into(), "cannot override a soul's chosen time".into()],
            banishment: "Never banish; thank it and drink blessed water to seal the blessing.".into(),
            tone: Tone::Positive,
            danger: "None — deeply restorative.".into(),
            is_custom: false.into(),
        },
        Entity {
            id: 104,
            name: "Angel of Death (Psychopomp)".into(),
            entity_type: EntityType::Angel,
            origin: "Folk belief worldwide; a gentle escort for souls crossing the veil.".into(),
            description: "A sacred guide that appears at the edge of death, easing fear and leading the soul onward.".into(),
            signs: vec!["apparition at the foot of a dying person's bed".into(), "room filling with stillness".into(),"scent of lilies or rain".into(), "pets gazing at an empty corner".into()],
            weaknesses: vec!["cannot be bribed or tricked".into(), "resistance causes struggle for the soul".into()],
            banishment: "Do not banish; light a candle for the crossing and speak a release blessing.".into(),
            tone: Tone::Neutral,
            danger: "Omen — not hostile; it comes for the dying, not the living.".into(),
            is_custom: false.into(),
        },
        Entity {
            id: 105,
            name: "Recording Angel".into(),
            entity_type: EntityType::Angel,
            origin: "Esoteric and mystical thought; the keeper of deeds, words, and unspoken intentions.".into(),
            description: "A silent witness that writes every act into memory. Often felt as judgment before sleep.".into(),
            signs: vec!["dreams of a great book or ledger".into(), "feeling weighed before mirrors".into(), "names appearing in dust or frost".into(), "sudden conviction to set things right".into()],
            weaknesses: vec!["truth and sincere remorse".into(), "righting wrongs before the threshold".into()],
            banishment: "Cannot be banished; live honestly and make amends quickly.".into(),
            tone: Tone::Positive,
            danger: "None directly — it reveals, it does not punish.".into(),
            is_custom: false.into(),
        },
        // More Spirits
        Entity {
            id: 110,
            name: "Ancestral Spirit".into(),
            entity_type: EntityType::Spirit,
            origin: "Global ancestor veneration; the deceased family line offering guidance and protection.".into(),
            description: "A family spirit that watches over descendants, appears in dreams, and can lend strength.".into(),
            signs: vec!["dream visits from dead relatives".into(), "heirlooms moving or warming".into(), "smell of their tobacco, perfume, or cooking".into(), "advice arriving in their voice".into()],
            weaknesses: vec!["disrespect or neglect of family rites".into(), "forgetting their names weakens the bond".into()],
            banishment: "Do not banish; set an offering, speak their name, and ask them to rest if intrusive.".into(),
            tone: Tone::Positive,
            danger: "Usually none — can become stern if dishonoured.".into(),
            is_custom: false.into(),
        },
        Entity {
            id: 111,
            name: "Familiar Spirit".into(),
            entity_type: EntityType::Spirit,
            origin: "European folk magic and witchcraft traditions; a tutelary spirit bound to a practitioner.".into(),
            description: "A spirit companion that assists in magic, warns of danger, and carries energy between worlds.".into(),
            signs: vec!["recurring animal or mask-shaped visions".into(), "tools moving into your hand at need".into(), "whispers while chanting".into(), "strong affinity for a particular stone or plant".into()],
            weaknesses: vec!["broken oaths or neglect".into(), "offering the wrong kind of energy".into()],
            banishment: "Release with gratitude and a closing rite; never banish harshly or it may take part of your luck.".into(),
            tone: Tone::Neutral,
            danger: "Low — depends on the bargain made.".into(),
            is_custom: false.into(),
        },
        Entity {
            id: 112,
            name: "Hungry Ghost".into(),
            entity_type: EntityType::Ghost,
            origin: "East Asian and Buddhist folklore; spirits with unfulfilled cravings from life.".into(),
            description: "A restless ghost driven by addiction, hunger, or attachment. It seeks what it could not release.".into(),
            signs: vec!["food spoiling unusually fast".into(), "smell of smoke, alcohol, or perfume".into(), "constant feeling of emptiness nearby".into(),"shadow at the table or pantry".into()],
            weaknesses: vec!["ritual food offerings".into(), "chanting names or releasing attachments".into(), "burning paper or symbolic gifts".into()],
            banishment: "Give an honest offering, speak its craving aloud and release it, then sweep salt water toward the door.".into(),
            tone: Tone::Negative,
            danger: "Low to moderate — drains vitality and peace.".into(),
            is_custom: false.into(),
        },
        Entity {
            id: 113,
            name: "Spectre".into(),
            entity_type: EntityType::Spirit,
            origin: "Western ghostlore; a visible, often translucent spirit of the dead.".into(),
            description: "A pale, transparent figure that appears in liminal hours, usually tied to a specific site or moment.".into(),
            signs: vec!["faint glowing figure after dusk".into(), "sudden silence when it appears".into(), "cold mist in a warm room".into(), "faces in old photographs changing".into()],
            weaknesses: vec!["daylight and fresh air".into(), "singing or ringing bells".into(), "acknowledging and releasing its story".into()],
            banishment: "Tell its story aloud, ring a bell nine times, and open every window at dawn.".into(),
            tone: Tone::Neutral,
            danger: "Low to moderate — mostly startling.".into(),
            is_custom: false.into(),
        },
        Entity {
            id: 114,
            name: "Apparition".into(),
            entity_type: EntityType::Ghost,
            origin: "Paranormal studies; a recognisable human figure witnessed by one or more people.".into(),
            description: "A clear image of a person, often recognised, appearing in ordinary surroundings for a brief time.".into(),
            signs: vec!["seeing a person who then vanishes".into(), "multiple witnesses describing the same figure".into(), "clothing from a specific era".into(), "silence and stillness around the sighting".into()],
            weaknesses: vec!["documenting the event calmly".into(), "salt across thresholds".into(), "asking it to depart at sunrise".into()],
            banishment: "Speak its name if known, explain that the living require the space, and lay salt at all doors.".into(),
            tone: Tone::Neutral,
            danger: "Usually none — can be unsettling.".into(),
            is_custom: false.into(),
        },
        Entity {
            id: 115,
            name: "Nature Spirit".into(),
            entity_type: EntityType::Spirit,
            origin: "Animist and pagan traditions; spirits dwelling in plants, stones, streams, and wild places.".into(),
            description: "A consciousness tied to a place in nature. Protective of its home and responsive to respect.".into(),
            signs: vec!["paths opening or closing in the woods".into(), "mushroom rings or peculiarly shaped stones".into(), "animals behaving as messengers".into(), "sudden wind after an offering".into()],
            weaknesses: vec!["litter, loud noise, and greed".into(), "iron sometimes repels, but offerings placate".into()],
            banishment: "Apologise, leave a small biodegradable offering, and retreat without looking back repeatedly.".into(),
            tone: Tone::Neutral,
            danger: "Low unless the land is harmed — then mischievous to dangerous.".into(),
            is_custom: false.into(),
        },
        // More Demons
        Entity {
            id: 120,
            name: "Incubus / Succubus".into(),
            entity_type: EntityType::Demon,
            origin: "Medieval demonology; spirits that seek intimacy and drain life force through desire.".into(),
            description: "A seductive entity that invades dreams and beds, feeding on fear, pleasure, and vitality.".into(),
            signs: vec!["sleep paralysis with a pressing presence".into(),"erotic or violating dreams that repeat".into(), "exhaustion after sleep".into(), "scratches on thighs or back".into()],
            weaknesses: vec!["iron bed frame or nails".into(),"salt around the bed".into(), "refusing engagement and prayers of sovereignty".into()],
            banishment: "Cleanse the bedroom with salt and sage, place iron near the bed, and assert loud refusal for three nights.".into(),
            tone: Tone::Negative,
            danger: "Moderate to high — drains energy and can traumatise.".into(),
            is_custom: false.into(),
        },
        Entity {
            id: 121,
            name: "Imp".into(),
            entity_type: EntityType::Demon,
            origin: "European folklore; small, minor demons of mischief and temptation.".into(),
            description: "A minor demon that delights in small chaos — moved keys, whispered doubts, and petty accidents.".into(),
            signs: vec!["objects vanishing then reappearing".into(), "snide whispers just out of hearing".into(), "trips, slips, and broken small items".into(), "laughter with no source".into()],
            weaknesses: vec!["order, cleanliness, and patience".into(), "mockery of its pranks".into(), "salt and laughter".into()],
            banishment: "Clean thoroughly, place a bowl of salt by the door, and insult its ambition with good humour.".into(),
            tone: Tone::Negative,
            danger: "Low to moderate — annoying, but can escalate if fed by anger.".into(),
            is_custom: false.into(),
        },
        Entity {
            id: 122,
            name: "Fallen Watcher".into(),
            entity_type: EntityType::Demon,
            origin: "Apocryphal traditions; angels who taught forbidden knowledge and were cast down.".into(),
            description: "A once-heavenly being swollen with hidden lore. It offers secrets in exchange for obedience.".into(),
            signs: vec!["dreams of books opening to hidden pages".into(), "sudden skills or knowledge you did not study".into(), "a charismatic voice demanding loyalty".into(), "cold fire in ritual candles".into()],
            weaknesses: vec!["reluctance to accept gifts".into(), "humility and refusal of secrets".into(), "names of power spoken with authority".into()],
            banishment: "Reject every gift, break any oath made in dreams, and seal thresholds with iron and psalm.".into(),
            tone: Tone::Negative,
            danger: "High — knowledge it gives always costs more than it appears.".into(),
            is_custom: false.into(),
        },
        Entity {
            id: 123,
            name: "Hellhound".into(),
            entity_type: EntityType::Demon,
            origin: "European folklore; black dogs associated with death, the crossroads, and the underworld.".into(),
            description: "A black, red-eyed dog of ill omen that patrols liminal places and warns of death.".into(),
            signs: vec!["giant black dog with glowing eyes".into(), "pad prints that burn or vanish".into(), "howling before a death".into(), "sulphur and wet fur smell".into()],
            weaknesses: vec!["crossroads offerings".into(), " refusal to show fear".into(), "iron and consecrated ground".into()],
            banishment: "Do not run; stand your ground, speak your name and lineage, and walk backward to holy ground.".into(),
            tone: Tone::Negative,
            danger: "Moderate to high — omen and guardian, not always attacker.".into(),
            is_custom: false.into(),
        },
        // More Fae
        Entity {
            id: 130,
            name: "Brownie".into(),
            entity_type: EntityType::Fae,
            origin: "Scottish folklore; a small household fae that helps in exchange for respect and gifts.".into(),
            description: "A helpful household spirit that tidies at night and protects the home when treated kindly.".into(),
            signs: vec!["small chores done overnight".into(), "food left out mysteriously nibbled".into(), "tiny footprints in flour".into(), "a feeling of safety in the house".into()],
            weaknesses: vec!["payments of clothing or coins offend it".into(),"rudeness or spying drives it away".into()],
            banishment: "Leave it cream and bread; if it must go, thank it and gift a small bowl of milk at the door.".into(),
            tone: Tone::Positive,
            danger: "None — becomes a boggart if insulted.".into(),
            is_custom: false.into(),
        },
        Entity {
            id: 131,
            name: "Boggart".into(),
            entity_type: EntityType::Fae,
            origin: "English and Scottish folklore; a household fae turned sour by insult or neglect.".into(),
            description: "A sour, thieving fae that causes bumps, bruises, and missing objects.".into(),
            signs: vec!["objects broken for no reason".into(), "pinches and bruises on sleepers".into(), "animals refusing to enter a room".into(), "milk curdling overnight".into()],
            weaknesses: vec!["kindness, patience, and a clean home".into(), "bells and clapping".into(), "rowan above the door".into()],
            banishment: "Do not show anger; clean the house, hang rowan, ring a bell, and offer bread and milk.".into(),
            tone: Tone::Negative,
            danger: "Low to moderate — malicious mischief.".into(),
            is_custom: false.into(),
        },
        Entity {
            id: 132,
            name: "Selkie".into(),
            entity_type: EntityType::Fae,
            origin: "Scottish, Irish, and Norse folklore; seal-fae who shed their skin to walk on land.".into(),
            description: "A seal-person bound to the sea. If its skin is stolen, it may be trapped on land until it is returned.".into(),
            signs: vec!["seals watching from the shore".into(), "a beautiful stranger who loves the sea".into(), "a hidden sealed skin in the home".into(), "storms following a theft".into()],
            weaknesses: vec!["possession of its seal skin".into(), "salt water and the call of the shore".into()],
            banishment: "Return the skin to the tide; do not force its stay.".into(),
            tone: Tone::Neutral,
            danger: "Low unless imprisoned — then the sea itself may turn harmful.".into(),
            is_custom: false.into(),
        },
        Entity {
            id: 133,
            name: "Nixie".into(),
            entity_type: EntityType::Fae,
            origin: "Germanic folklore; a water spirit that dwells in rivers and mills.".into(),
            description: "A beautiful water fae who lurks at riverbanks, sometimes drowning the careless, sometimes teaching music.".into(),
            signs: vec!["music rising from still water".into(), "ripples against the current".into(), "long hair glimpsed beneath the surface".into(), "drowning in places known to be safe".into()],
            weaknesses: vec!["iron and steel".into(), "calling its true name".into(), "throwing salt or bread into the water".into()],
            banishment: "Never mock it; leave bread and salt at the bank, speak its name, and stay away at dusk.".into(),
            tone: Tone::Neutral,
            danger: "Moderate — capricious and deadly near water.".into(),
            is_custom: false.into(),
        },
        Entity {
            id: 134,
            name: "Pixie".into(),
            entity_type: EntityType::Fae,
            origin: "Cornish and English folklore; tiny winged fae fond of dancing and leading travellers astray.".into(),
            description: "A small, quick fae that enjoys tricks, dances, and confusing paths in the countryside.".into(),
            signs: vec!["tiny lights bobbing in fields".into(), "laughter in hedgerows".into(), "travelers losing time on known paths".into(), "milk souring after a night walk".into()],
            weaknesses: vec!["turning clothes inside out".into(),"cold iron".into(), "staying on the path and ignoring calls".into()],
            banishment: "Turn your coat inside out, carry iron, and retrace your steps without acknowledging them.".into(),
            tone: Tone::Neutral,
            danger: "Low — mostly disorientation and mischief.".into(),
            is_custom: false.into(),
        },
        // More Shades
        Entity {
            id: 140,
            name: "Night Hag".into(),
            entity_type: EntityType::Shade,
            origin: "Sleep-paralysis folklore worldwide; a dark figure that sits on the chest and steals breath.".into(),
            description: "A heavy shadow that rides the chest during paralysis, feeding on terror and helplessness.".into(),
            signs: vec!["waking unable to move".into(), "pressure on chest".into(), "a looming dark shape".into(), "gasping for air upon waking".into()],
            weaknesses: vec!["sleeping on the side".into(), "regular rest and reduced stress".into(), "salt and protective amulets".into()],
            banishment: "Cleanse the room, sleep on your side, keep a lit candle or salt nearby, and refuse fear.".into(),
            tone: Tone::Negative,
            danger: "Moderate — terrifying but rarely physically dangerous.".into(),
            is_custom: false.into(),
        },
        Entity {
            id: 141,
            name: "Gloomshade".into(),
            entity_type: EntityType::Shade,
            origin: "Modern occult terminology; a dense patch of despair-born shadow.".into(),
            description: "A thick shadow that pools in corners where grief, depression, or prolonged anger has gathered.".into(),
            signs: vec!["corners that feel darker than they should".into(), "sudden heaviness in a room".into(),"plants dying in one spot".into(), "people weeping without knowing why".into()],
            weaknesses: vec!["sunlight, fresh air, and laughter".into(), "singing, bells, and salt scrub".into()],
            banishment: "Open all windows at noon, wash floors with salt water, burn rosemary, and invite joyful company.".into(),
            tone: Tone::Negative,
            danger: "Low to moderate — emotional drain.".into(),
            is_custom: false.into(),
        },
        // More Wraiths
        Entity {
            id: 150,
            name: "Mournful Wraith".into(),
            entity_type: EntityType::Wraith,
            origin: "Folk accounts of spirits unable to grieve or let go.".into(),
            description: "A wraith made of grief. It weeps, calls names, and drains colour from the room.".into(),
            signs: vec!["sound of weeping in empty rooms".into(), "names whispered on the wind".into(), "colours seeming grey for a moment".into(), "pets grieving without cause".into()],
            weaknesses: vec!["mourning rituals and spoken grief".into(), "rosemary, lavender, and release rites".into()],
            banishment: "Acknowledge the loss, name it aloud, burn rosemary, and tell the wraith it is allowed to rest.".into(),
            tone: Tone::Neutral,
            danger: "Moderate — drains joy and colour from life.".into(),
            is_custom: false.into(),
        },
        Entity {
            id: 151,
            name: "Drowned Wraith".into(),
            entity_type: EntityType::Wraith,
            origin: "Folklore of lakes, rivers, and burial at sea; spirits of those taken by water.".into(),
            description: "A water-bound wraith that pulls toward the depths, seeking company for its cold loneliness.".into(),
            signs: vec!["hands beneath the water's surface".into(), "hair floating against the current".into(), "whispers from bridges or docks".into(), "cold patches over water".into()],
            weaknesses: vec!["running water and salt".into(), "bells and prayers for the drowned".into()],
            banishment: "Pray for the soul by moving water, cast bread and salt, and avoid the site until the stillness clears.".into(),
            tone: Tone::Negative,
            danger: "High near water — can pull the living under.".into(),
            is_custom: false.into(),
        },
        // More Poltergeists
        Entity {
            id: 160,
            name: "Stone-Throwing Spirit".into(),
            entity_type: EntityType::Poltergeist,
            origin: "Global poltergeist accounts; focuses on thrown stones, pebbles, and gravel.".into(),
            description: "A poltergeist manifestation that pelts a place with small stones, often from impossible angles.".into(),
            signs: vec!["pebbles hitting windows from inside".into(), "gravel appearing in rooms".into(), "stones falling from ceilings".into(), "dents in walls with no source".into()],
            weaknesses: vec!["identifying the emotional focus".into(), "placing iron in every corner".into(), "calming the household".into()],
            banishment: "Find the person at the centre of the distress, bless each room with salt and iron, and speak a firm cease command.".into(),
            tone: Tone::Negative,
            danger: "Moderate — can bruise and break glass.".into(),
            is_custom: false.into(),
        },
        Entity {
            id: 161,
            name: "Kinetic Spirit".into(),
            entity_type: EntityType::Poltergeist,
            origin: "Parapsychological model; a spirit or living-agent projection of raw psychokinesis.".into(),
            description: "A burst of invisible force that slams doors, hurls furniture, and responds to intense emotion.".into(),
            signs: vec!["doors slamming in sequence".into(), "heavy objects sliding".into(), "lights exploding".into(), "violence during arguments".into()],
            weaknesses: vec!["reducing emotional charge".into(), "grounding with salt and iron".into(), "calm voices and steady breathing".into()],
            banishment: "De-escalate everyone in the house, ground the energy with salt under thresholds, and have a neutral third party speak release.".into(),
            tone: Tone::Negative,
            danger: "High — can injure through flying objects.".into(),
            is_custom: false.into(),
        },
    ]
}
