use crate::models::{MoonPhaseRequirement, Offering};

pub fn build_offerings() -> Vec<Offering> {
    vec![
        // Norse
        Offering {
            id: 1,
            name: "Hearth Offering to Odin".into(),
            deity_id: 1,
            religion: "Norse".into(),
            items: vec!["Mead".into(), "Bread".into(), "Beef or mutton".into(), "Twine or coarse wool".into()],
            instructions: "Pour mead into a bowl and set bread beside it. Speak a brief verse or personal oath while facing north. Burn a small piece of wool as gift of effort. Leave the food outdoors or dispose of it respectfully after the rite.".into(),
            purpose: "Gain wisdom, clarity, or strength before a major decision or battle.".into(),
            moon_phase: MoonPhaseRequirement::WaxingCrescent,
            best_time: "Wednesday, dawn or twilight".into(),
            warnings: vec!["Do not swear oaths you cannot keep.".into()],
            source_note: "Common Heathen reconstructions".into(),
            is_custom: false,
        },
        Offering {
            id: 2,
            name: "Freyja's Gold and Flower Rite".into(),
            deity_id: 5,
            religion: "Norse".into(),
            items: vec!["Strawberries or apples".into(), "Gold-coloured honey".into(), "Roses or marigolds".into(), "Amber or brass token".into()],
            instructions: "Arrange flowers around a central dish of fruit drizzled with honey. Hold the amber token and speak of what you desire with courage. Return fruit to the earth when finished.".into(),
            purpose: "Honour love, beauty, seidr, and bold desire.".into(),
            moon_phase: MoonPhaseRequirement::FullMoon,
            best_time: "Friday, midnight under moonlight".into(),
            warnings: vec![].into(),
            source_note: "Norse pagan practice".into(),
            is_custom: false,
        },
        // Greek
        Offering {
            id: 3,
            name: "Libation to Hestia".into(),
            deity_id: 0,
            religion: "Greek".into(),
            items: vec!["Olive oil".into(), "Wine or fresh water".into(), "A small handful of barley".into()],
            instructions: "Pour a small measure of oil or wine onto the earth or hearth flame, scattering barley after it. Offer first to Hestia before any other rite.".into(),
            purpose: "Sanctify the home, kitchen, or ritual space.".into(),
            moon_phase: MoonPhaseRequirement::Any,
            best_time: "Before any major offering or family meal".into(),
            warnings: vec!["Never pour excessive alcohol near open flames.".into()],
            source_note: "Hellenic reconstruction".into(),
            is_custom: false,
        },
        // Egyptian
        Offering {
            id: 4,
            name: "Bread and Beer for the Ka".into(),
            deity_id: 0,
            religion: "Egyptian".into(),
            items: vec!["Flatbread".into(),"Beer or barley drink".into(),"Onion or garlic".into(),"Lotus or lily flower".into()],
            instructions: "Present the meal on a clean plate, speak the deity's name, and leave it in a place of honour for a short time before returning food to nature.".into(),
            purpose: "Sustain the Ka and invite divine presence.".into(),
            moon_phase: MoonPhaseRequirement::Any,
            best_time: "Sunrise or noon".into(),
            warnings: vec!["Avoid offering items that spoil quickly in heat.".into()],
            source_note: "Kemetic practice".into(),
            is_custom: false,
        },
        // Christianity
        Offering {
            id: 5,
            name: "Firstfruits Prayer Offering".into(),
            deity_id: 52,
            religion: "Christianity".into(),
            items: vec!["Bread or wine".into(),"A written prayer or tithe".into(),"Olive oil".into()],
            instructions: "Set aside a portion of your meal or income with gratitude. Speak or read a psalm, then share the food with someone in need or offer the tithe through your community.".into(),
            purpose: "Express gratitude, trust, and charitable commitment.".into(),
            moon_phase: MoonPhaseRequirement::Any,
            best_time: "Sunday morning or before a meal".into(),
            warnings: vec![].into(),
            source_note: "General Christian piety".into(),
            is_custom: false,
        },
        Offering {
            id: 6,
            name: "Votive Candle and Psalm".into(),
            deity_id: 52,
            religion: "Christianity".into(),
            items: vec!["White candle".into(),"Psalm or personal petition".into(),"Holy water or blessed oil".into()],
            instructions: "Light the candle with a prayer, read or recite a psalm, and sit in silence for a set time. Extinguish the candle safely when done.".into(),
            purpose: "Seek guidance, protection, or intercession.".into(),
            moon_phase: MoonPhaseRequirement::Any,
            best_time: "Evening or during personal prayer time".into(),
            warnings: vec!["Never leave a burning candle unattended.".into()],
            source_note: "Catholic/Orthodox devotion".into(),
            is_custom: false,
        },
        // Hindu
        Offering {
            id: 7,
            name: "Simple Puja Plate".into(),
            deity_id: 0,
            religion: "Hindu".into(),
            items: vec!["Rice or kumkum".into(),"Incense or lamp".into(),"Flowers".into(),"Fruit or sweets".into()],
            instructions: "Light the lamp or incense, offer flowers and rice with a mantra or the deity's name, then distribute the prasad.".into(),
            purpose: "Daily worship and cultivate bhakti.".into(),
            moon_phase: MoonPhaseRequirement::Any,
            best_time: "Morning or evening aarti".into(),
            warnings: vec!["Use food-safe materials only.".into()],
            source_note: "Hindu household puja".into(),
            is_custom: false,
        },
        // Shinto
        Offering {
            id: 8,
            name: "Shinsen Offering".into(),
            deity_id: 0,
            religion: "Shinto".into(),
            items: vec!["Sake or water".into(),"Rice or salt".into(),"Seasonal fruit".into(),"Sakaki branch".into()],
            instructions: "Arrange offerings on a clean white cloth or small stand, bow twice, clap twice, and bow once while offering thanks. Remove and consume or return items after a respectful period.".into(),
            purpose: "Honour Kami and maintain harmony with the local spirits.".into(),
            moon_phase: MoonPhaseRequirement::Any,
            best_time: "New moon or seasonal festival".into(),
            warnings: vec!["Keep offerings fresh; stale food is disrespectful.".into()],
            source_note: "Shinto household practice".into(),
            is_custom: false,
        },
        // Celtic
        Offering {
            id: 9,
            name: "Land Spirit Bowl".into(),
            deity_id: 0,
            religion: "Celtic".into(),
            items: vec!["Milk or cream".into(),"Oats or honey".into(),"Whiskey or ale".into(),"A small silver coin".into()],
            instructions: "Place the bowl at the threshold, by a tree, or on a windowsill. Speak an invitation to the local spirits. Leave overnight, then pour into the earth.".into(),
            purpose: "Build friendship with land spirits and ancestors of place.".into(),
            moon_phase: MoonPhaseRequirement::FullMoon,
            best_time: "Full moon or Beltane/Samhain".into(),
            warnings: vec!["Do not leave food where it will attract pests.".into()],
            source_note: "Celtic folk practice".into(),
            is_custom: false,
        },
        // Satanism
        Offering {
            id: 10,
            name: "Symbolic Self-Dedication".into(),
            deity_id: 0,
            religion: "Satanism".into(),
            items: vec!["Black candle".into(),"A signed personal affirmation".into(),"A drop of your own blood (optional)".into()],
            instructions: "Burn the affirmation as a sign of intent, meditate on personal sovereignty, and extinguish the candle deliberately. Blood is optional and must be obtained safely.".into(),
            purpose: "Affirm autonomy, will, and rejection of spiritual coercion.".into(),
            moon_phase: MoonPhaseRequirement::Any,
            best_time: "A personally significant date".into(),
            warnings: vec!["Avoid unsafe blood practices; do not harm others.".into()],
            source_note: "Modern Satanic self-ritual".into(),
            is_custom: false,
        },
    ]
}
