use crate::models::{MoonPhaseRequirement, Spell, SpellCategory};

pub fn build_spells() -> Vec<Spell> {
    vec![
        Spell {
            id: 0,
            name: "Smoke of Return".into(),
            category: SpellCategory::Cleansing,
            purpose: "Clear a space of stagnant or unwelcome energies and reset it for new work.".into(),
            ingredients: vec!["dried rosemary".into(), "white sage or mugwort".into(), "a heat-safe dish".into()],
            steps: vec![
                "Light the herbs and let them smoulder into smoke rather than flame.".into(),
                "Walk the space clockwise, fanning smoke into corners and thresholds.".into(),
                "Speak your intention aloud: 'What is not mine, leave; what is mine, stay.'".into(),
                "Extinguish safely and leave a window open until the air clears.".into(),
            ],
            warnings: vec!["Never leave burning herbs unattended.".into(), "Avoid if you have asthma or birds in the home.".into()],
            related_entity_ids: vec![0, 3],
            source_note: "Common folk practice across European and North American witchcraft.".into(),
            difficulty: 2,
            risk_rating: 2,
            is_custom: false,
            moon_phase: MoonPhaseRequirement::NewMoon,
        },
        Spell {
            id: 1,
            name: "Threshold Guard".into(),
            category: SpellCategory::Protection,
            purpose: "Protect a doorway from spirits or ill intentions.".into(),
            ingredients: vec!["salt".into(), "black pepper".into(), "a pinch of graveyard dirt (optional)".into()],
            steps: vec![
                "Mix salt and pepper in your dominant hand.".into(),
                "Lay a thin line across the threshold while stating what is barred.".into(),
                "Renew after heavy rain, arguments, or unwanted visitors.".into(),
            ],
            warnings: vec!["This is a barrier; do not trap yourself inside.".into()],
            related_entity_ids: vec![],
            source_note: "Threshold magic appears in worldwide folk traditions.".into(),
            difficulty: 2,
            risk_rating: 2,
            is_custom: false,
            moon_phase: MoonPhaseRequirement::FirstQuarter,
        },
        Spell {
            id: 2,
            name: "Mirror Gaze".into(),
            category: SpellCategory::Divination,
            purpose: "Receive impressions, names, or symbols by scrying in a dark mirror.".into(),
            ingredients: vec!["a black mirror or bowl of dark water".into(), "one black candle".into(), "frankincense".into()],
            steps: vec![
                "Darken the room except for the candle behind the mirror.".into(),
                "Gaze gently at the mirror surface without focusing sharply.".into(),
                "Breathe slowly and note any shapes, words, or sensations.".into(),
                "Close by thanking the mirror and covering it.".into(),
            ],
            warnings: vec!["Do not scry while emotionally distressed or exhausted.".into(), "Banish by laughing or clapping if you feel watched.".into()],
            related_entity_ids: vec![],
            source_note: "Scrying has roots in Renaissance Europe and older Near Eastern practices.".into(),
            difficulty: 2,
            risk_rating: 2,
            is_custom: false,
            moon_phase: MoonPhaseRequirement::FullMoon,
        },
        Spell {
            id: 3,
            name: "Knot of Binding".into(),
            category: SpellCategory::Binding,
            purpose: "Restrain someone's harmful actions without causing them direct harm.".into(),
            ingredients: vec!["black cord".into(), "a photograph or written name".into(), "candle wax".into()],
            steps: vec![
                "Hold the cord and focus on the specific behaviour, not the person.".into(),
                "Tie nine knots, speaking the binding at each.".into(),
                "Seal the knots with wax and hide the cord where it will not be disturbed.".into(),
                "Untie and burn when the danger has passed.".into(),
            ],
            warnings: vec!["Bindings can backlash if used for revenge.".into(), "Seek mundane solutions alongside magical ones.".into()],
            related_entity_ids: vec![],
            source_note: "Cord and knot magic is found in British, African diaspora, and sea-folk traditions.".into(),
            difficulty: 2,
            risk_rating: 2,
            is_custom: false,
            moon_phase: MoonPhaseRequirement::FullMoon,
        },
        Spell {
            id: 4,
            name: "Return to Sender".into(),
            category: SpellCategory::Curses,
            purpose: "Mirror a curse or hostile magic back to its source.".into(),
            ingredients: vec!["a small mirror".into(), "black salt".into(), "cayenne pepper".into()],
            steps: vec![
                "Place the mirror face-down on your altar.".into(),
                "Sprinkle black salt and pepper across its back in a cross.".into(),
                "Speak: 'What was sent against me returns to its maker.'".into(),
                "Bury the mirror near a crossroads or at the property edge.".into(),
            ],
            warnings: vec!["Only use when you are certain you are under attack.".into(), "Expect escalation; prepare protection first.".into()],
            related_entity_ids: vec![5, 6],
            source_note: "Mirror-return spells occur in Hoodoo and European folk witchcraft.".into(),
            difficulty: 2,
            risk_rating: 2,
            is_custom: false,
            moon_phase: MoonPhaseRequirement::FullMoon,
        },
        Spell {
            id: 5,
            name: "Door to the Fae".into(),
            category: SpellCategory::Summoning,
            purpose: "Invite fae influence for inspiration, luck, or hidden knowledge.".into(),
            ingredients: vec!["milk or cream".into(), "honey".into(), "a small bell".into(), "rowan or hawthorn twig".into()],
            steps: vec![
                "Leave the offering outdoors at twilight near elder, hawthorn, or a fairy ring.".into(),
                "Ring the bell three times and speak your request plainly.".into(),
                "Walk away without looking back.".into(),
                "If accepted, gifts may appear; if refused, do not repeat for a year and a day.".into(),
            ],
            warnings: vec!["Never eat or drink anything offered by the fae.".into(), "Avoid inviting them inside your home.".into()],
            related_entity_ids: vec![7, 8],
            source_note: "British Isles fairy-lore and cautionary folk practice.".into(),
            difficulty: 2,
            risk_rating: 2,
            is_custom: false,
            moon_phase: MoonPhaseRequirement::FullMoon,
        },
        Spell {
            id: 6,
            name: "Witch's Bottle".into(),
            category: SpellCategory::Protection,
            purpose: "Absorb and trap hostile magic aimed at the home.".into(),
            ingredients: vec!["a glass jar with lid".into(), "rusty nails".into(), "urine or pins".into(), "black thread".into()],
            steps: vec![
                "Fill the jar with sharp and personal items.".into(),
                "Seal it while naming every harm you wish turned away.".into(),
                "Bury it beneath the threshold or hide it inside a wall.".into(),
                "Replace if the jar cracks or the home is threatened.".into(),
            ],
            warnings: vec!["Do not open once sealed; dispose of cracked bottles at a crossroads.".into()],
            related_entity_ids: vec![5],
            source_note: "Penn Dutch and British witch-bottle traditions.".into(),
            difficulty: 2,
            risk_rating: 2,
            is_custom: false,
            moon_phase: MoonPhaseRequirement::FullMoon,
        },
        Spell {
            id: 7,
            name: "Spirit Lamp".into(),
            category: SpellCategory::Divination,
            purpose: "Create conditions for a spirit to answer yes-or-no questions.".into(),
            ingredients: vec!["a white candle".into(), "a bowl of water".into(), "a pinch of salt".into()],
            steps: vec![
                "Sit in silence and light the candle after midnight.".into(),
                "Ask three times whether the spirit is present.".into(),
                "Read the flame: steady means yes, flickering wild means no or refusal.".into(),
                "Blow out the candle and pour salt into the water to close.".into(),
            ],
            warnings: vec!["Begin and end every session with a closing statement.".into(), "If the flame goes out on its own, stop immediately.".into()],
            related_entity_ids: vec![3, 4],
            source_note: "Common in spiritist and folk necromancy methods.".into(),
            difficulty: 2,
            risk_rating: 2,
            is_custom: false,
            moon_phase: MoonPhaseRequirement::LastQuarter,
        },
        Spell {
            id: 8,
            name: "Healing Hive".into(),
            category: SpellCategory::Healing,
            purpose: "Support recovery from illness or emotional injury.".into(),
            ingredients: vec!["cinnamon".into(), "chamomile".into(), "a beeswax candle".into(), "a photo or lock of hair".into()],
            steps: vec![
                "Make a small sachet of the herbs and place it with the candle.".into(),
                "Light the candle and speak the person's name seven times.".into(),
                "Let the candle burn safely in installments until gone.".into(),
                "Bury the remaining herbs under a healthy plant.".into(),
            ],
            warnings: vec!["This supports, not replaces, medical care.".into(), "Do not perform for someone without consent.".into()],
            related_entity_ids: vec![],
            source_note: "Adapted from hoodoo healing candles and herb bundles.".into(),
            difficulty: 2,
            risk_rating: 2,
            is_custom: false,
            moon_phase: MoonPhaseRequirement::Any,
        },
        Spell {
            id: 9,
            name: "Veil of Glamour".into(),
            category: SpellCategory::Glamour,
            purpose: "Make yourself harder to notice or remember in a crowd.".into(),
            ingredients: vec!["a silver ring or pendant".into(), "moonwater".into(), "lavender oil".into()],
            steps: vec![
                "Anoint the jewellery with one drop of lavender oil.".into(),
                "Pass it through moonwater smoke or mist.".into(),
                "Wear it while saying: 'Eyes pass over, minds let go.'".into(),
                "Recharge under the waning moon.".into(),
            ],
            warnings: vec!["Do not use to evade justice or harm others.".into()],
            related_entity_ids: vec![],
            source_note: "Glamour magic appears in modern witchcraft and classical literature.".into(),
            difficulty: 2,
            risk_rating: 2,
            is_custom: false,
            moon_phase: MoonPhaseRequirement::WaxingGibbous,
        },
        Spell {
            id: 10,
            name: "Exorcism of Shadows".into(),
            category: SpellCategory::Cleansing,
            purpose: "Drive out a hostile shade or wraith from a dwelling.".into(),
            ingredients: vec!["iron nails".into(), "salt".into(), "sage".into(), "a strong voice".into()],
            steps: vec![
                "Open every door and window.".into(),
                "Begin at the lowest point of the house and work upward.".into(),
                "Command the entity to leave by name if known; use iron and salt at exits.".into(),
                "Seal thresholds with salt and close windows from the inside out.".into(),
            ],
            warnings: vec!["High risk; have an exit plan and do not work alone.".into(), "Seek experienced help for demons or oppressors.".into()],
            related_entity_ids: vec![1, 9, 5, 6],
            source_note: "Composite of folk exorcism and house-clearing methods.".into(),
            difficulty: 2,
            risk_rating: 2,
            is_custom: false,
            moon_phase: MoonPhaseRequirement::Any,
        },
        // Love
        Spell {
            id: 11,
            name: "Sweetening Jar".into(),
            category: SpellCategory::Love,
            purpose: "Soften a relationship or draw kindness and affection toward you.".into(),
            ingredients: vec!["a small jar with lid".into(), "honey".into(), "rose petals".into(), "cinnamon".into(), "paper and pen".into()],
            steps: vec![
                "Write your name and the desired quality of the relationship on paper.".into(),
                "Roll the paper toward you and place it in the jar.".into(),
                "Cover with honey, rose petals, and a pinch of cinnamon.".into(),
                "Seal it, shake it daily while speaking sweet words, and keep it for a moon cycle.".into(),
            ],
            warnings: vec!["Never work to control a specific person's will.".into(), "Aim at the relationship's quality, not a targeted individual.".into()],
            related_entity_ids: vec![],
            source_note: "Hoodoo honey-jar work adapted for romance.".into(),
            difficulty: 1,
            risk_rating: 1,
            is_custom: false,
            moon_phase: MoonPhaseRequirement::WaxingCrescent,
        },
        Spell {
            id: 12,
            name: "Rose Attraction Bath".into(),
            category: SpellCategory::Love,
            purpose: "Open the heart and make yourself magnetic to love and friendship.".into(),
            ingredients: vec!["rose petals".into(), "honey".into(), "cinnamon stick".into(), "a handful of sea salt".into()],
            steps: vec![
                "Steep the petals, cinnamon, and honey in warm water as you bathe.".into(),
                "Pour the water over yourself from shoulders down seven times.".into(),
                "Speak what love you welcome, without naming a person.".into(),
                "Pat dry and let the first drops fall on the earth outside.".into(),
            ],
            warnings: vec!["Never work to manipulate another's affection.".into()],
            related_entity_ids: vec![],
            source_note: "Afro-Caribbean and hoodoo attraction-bath practice.".into(),
            difficulty: 1,
            risk_rating: 1,
            is_custom: false,
            moon_phase: MoonPhaseRequirement::WaxingCrescent,
        },
        // Prosperity
        Spell {
            id: 13,
            name: "Green Candle Abundance".into(),
            category: SpellCategory::Prosperity,
            purpose: "Draw steady income, opportunity, and material stability.".into(),
            ingredients: vec!["a green pillar candle".into(), "basil leaves".into(), "a coin".into(), "olive or money oil".into()],
            steps: vec![
                "Dress the candle bottom-to-top with money oil.".into(),
                "Ring the base with basil leaves and the coin.".into(),
                "Light it and name the stream of provision you invite.".into(),
                "Let it burn in sessions; carry the coin as a token when finished.".into(),
            ],
            warnings: vec!["Magic supports, not replaces, budgeting and job searching.".into()],
            related_entity_ids: vec![],
            source_note: "Candle-magic prosperity work common in hoodoo and folk craft.".into(),
            difficulty: 1,
            risk_rating: 1,
            is_custom: false,
            moon_phase: MoonPhaseRequirement::WaxingCrescent,
        },
        Spell {
            id: 14,
            name: "Cornucopia Pouch".into(),
            category: SpellCategory::Prosperity,
            purpose: "Keep steady abundance flowing into home and table.".into(),
            ingredients: vec!["a green or gold charm pouch".into(), "wheat or oats".into(), "a small citrine".into(), "bay leaf".into()],
            steps: vec![
                "Fill the pouch with wheat, the stone, and a bay leaf.".into(),
                "Hold it at your heart and speak thanks for what already flows.".into(),
                "Hang it near where money or food enters the home.".into(),
                "Refresh the herbs at each new moon.".into(),
            ],
            warnings: vec!["Gratitude first; greed tattoos the spell with hunger.".into()],
            related_entity_ids: vec![11],
            source_note: "European harvest-charm tradition.".into(),
            difficulty: 1,
            risk_rating: 1,
            is_custom: false,
            moon_phase: MoonPhaseRequirement::NewMoon,
        },
        // Luck
        Spell {
            id: 15,
            name: "Lucky Acorn Charm".into(),
            category: SpellCategory::Luck,
            purpose: "Carry field-grade good luck for games, travel, and chance meetings.".into(),
            ingredients: vec!["an acorn or four-leaf clover".into(), "a green thread".into(), "spearmint leaf".into()],
            steps: vec![
                "Dry the acorn in sunlight for a full day.".into(),
                "Wrap its stem with green thread, tucking the mint beneath the windings.".into(),
                "Speak your luck request nine times as you tie the final knot.".into(),
                "Carry it in pocket or bag where it will be jostled often.".into(),
            ],
            warnings: vec!["Luck charms fade with bad faith; keep your word.".into()],
            related_entity_ids: vec![11],
            source_note: "European and Appalachian folk luck charms.".into(),
            difficulty: 1,
            risk_rating: 1,
            is_custom: false,
            moon_phase: MoonPhaseRequirement::WaxingGibbous,
        },
        Spell {
            id: 16,
            name: "Quick-Luck Floor Wash".into(),
            category: SpellCategory::Luck,
            purpose: "Turn a run of bad luck in a home around within one week.".into(),
            ingredients: vec!["chamomile tea".into(), "a pinch of salt".into(), "lemon peel".into(), "a bucket of clean water".into()],
            steps: vec![
                "Brew the tea strong and cool it, then add to the wash water.".into(),
                "Add lemon peel and salt, stirring sunwise.".into(),
                "Mop the floors from the back door outward, speaking luck at each room.".into(),
                "Pour the remaining water out the front door, never down the drain inside.".into(),
            ],
            warnings: vec!["Do not use where pets may lick the floor before it dries.".into()],
            related_entity_ids: vec![],
            source_note: "Hoodoo floor-wash practice for shifting a home's fortune.".into(),
            difficulty: 1,
            risk_rating: 1,
            is_custom: false,
            moon_phase: MoonPhaseRequirement::FirstQuarter,
        },
        // Banishment
        Spell {
            id: 17,
            name: "Black Candle Cut".into(),
            category: SpellCategory::Banishment,
            purpose: "Sever an unwanted tie, habit, or lingering presence and close the door after it.".into(),
            ingredients: vec!["a black candle".into(), "black thread".into(), "scissors".into()],
            steps: vec![
                "Tie one end of the thread to the candle, the other to a token of the unwanted tie.".into(),
                "Light the candle and name what must leave, without anger.".into(),
                "Cut the thread cleanly and let the candle burn down fully.".into(),
                "Bury the token away from the home and wash your hands in cold salted water.".into(),
            ],
            warnings: vec!["Never banish a protection, guardian, or helpful spirit by mistake — know your target.".into()],
            related_entity_ids: vec![5, 6],
            source_note: "Folk candle-and-sever practice adapted from European banishing rites.".into(),
            difficulty: 2,
            risk_rating: 3,
            is_custom: false,
            moon_phase: MoonPhaseRequirement::WaningGibbous,
        },
        Spell {
            id: 18,
            name: "Iron and Rowan Sweep".into(),
            category: SpellCategory::Banishment,
            purpose: "Drive lingering hostile spirits out of a house and keep them out.".into(),
            ingredients: vec!["a small iron nail".into(), "rowan twigs".into(), "salted water".into(), "a red ribbon".into()],
            steps: vec![
                "Bind nail and rowan with the red ribbon into a small cross.".into(),
                "Carry it through every room, tapping walls and corners.".into(),
                "Wash thresholds with the salted water, moving outward.".into(),
                "Nail or hang the cross above the main door, point down.".into(),
            ],
            warnings: vec!["Do not use against fae you have bargained with; iron breaks each oath.".into()],
            related_entity_ids: vec![1, 9, 7],
            source_note: "British and Iron Age apotropaic custom.".into(),
            difficulty: 2,
            risk_rating: 2,
            is_custom: false,
            moon_phase: MoonPhaseRequirement::LastQuarter,
        },
        // Dream
        Spell {
            id: 19,
            name: "Dream Pillow of Remembering".into(),
            category: SpellCategory::Dream,
            purpose: "Sharpen dream recall and draw guidance into rest.".into(),
            ingredients: vec!["dried mugwort".into(), "lavender".into(), "a small cloth pillow".into(), "flaxseed".into()],
            steps: vec![
                "Fill the pouch with equal mugwort, lavender, and flaxseed.".into(),
                "Hold it to your third eye and speak what you wish to learn from dream.".into(),
                "Tuck it under your pillow or beside your bed each night.".into(),
                "Record dreams in the morning without editing.".into(),
            ],
            warnings: vec!["Mugwort can cause vivid or restless dreams; begin sparingly.".into(), "Avoid in pregnancy.".into()],
            related_entity_ids: vec![],
            source_note: "European dream-pillow herbs used since antiquity.".into(),
            difficulty: 1,
            risk_rating: 1,
            is_custom: false,
            moon_phase: MoonPhaseRequirement::FullMoon,
        },
        Spell {
            id: 20,
            name: "Quiet Sleep Wards".into(),
            category: SpellCategory::Dream,
            purpose: "Guard sleep from nightmares, incubus, and intrusive dreaming.".into(),
            ingredients: vec!["a white candle".into(), "chamomile or lavender oil".into(), "a pinch of salt".into(), "a glass of water".into()],
            steps: vec![
                "Anoint the bed's four corners with oil and salt.".into(),
                "Light the candle and speak: 'Only peace may stand at this bed.'".into(),
                "Leave the glass of water on the nightstand to absorb the night's weight.".into(),
                "Empty and refill the glass each morning without drinking it.".into(),
            ],
            warnings: vec!["Keep candle flame clear of bedding and curtains.".into()],
            related_entity_ids: vec![120, 140],
            source_note: "Composite of folk sleep-warding across Europe and the Mediterranean.".into(),
            difficulty: 1,
            risk_rating: 1,
            is_custom: false,
            moon_phase: MoonPhaseRequirement::Any,
        },
        // Weather
        Spell {
            id: 21,
            name: "Rain Calling".into(),
            category: SpellCategory::Weather,
            purpose: "Invite gentle rain for gardens, fields, or personal cleansing.".into(),
            ingredients: vec!["a bowl of water".into(), "a blue or grey candle".into(), "a sprig of moss".into()],
            steps: vec![
                "Set the bowl outside or on a west-facing windowsill.".into(),
                "Light the candle and describe the rain you want, its weight and length.".into(),
                "Drip channel or broom the bowl's water skyward in rhythm.".into(),
                "Pour the bowl out when clouds gather; thank the sky regardless.".into(),
            ],
            warnings: vec!["Ask for what is needed, not for what would harm neighbours.".into()],
            related_entity_ids: vec![11],
            source_note: "Agricultural weather-magic across Europe and West Africa.".into(),
            difficulty: 3,
            risk_rating: 2,
            is_custom: false,
            moon_phase: MoonPhaseRequirement::WaxingCrescent,
        },
        Spell {
            id: 22,
            name: "Storm Quelling".into(),
            category: SpellCategory::Weather,
            purpose: "Ease a dangerous storm passing near home or travellers on the road.".into(),
            ingredients: vec!["a handful of salt".into(), "a white candle".into(), "a knotted grey cord".into()],
            steps: vec![
                "Light the candle in a window facing the storm.".into(),
                "Loosen, do not untie, the knots while speaking the storm down in tone, not in harm.".into(),
                "Scatter a ring of salt outside the main door as a boundary of peace.".into(),
                "Snuff the candle only after the thunder fades.".into(),
            ],
            warnings: vec!["Never bind wind or lightning outright — only ease its path.".into()],
            related_entity_ids: vec![11],
            source_note: "Sailor and farming weather-charm tradition.".into(),
            difficulty: 3,
            risk_rating: 2,
            is_custom: false,
            moon_phase: MoonPhaseRequirement::LastQuarter,
        },
        // Blessing
        Spell {
            id: 23,
            name: "Hearth Blessing".into(),
            category: SpellCategory::Blessing,
            purpose: "Bless a new home, or renew warmth and protection in an old one.".into(),
            ingredients: vec!["bread".into(), "honey".into(), "a white candle".into(), "a pinch of rosemary".into()],
            steps: vec![
                "Light the candle at the hearth or kitchen table.".into(),
                "Break bread and daub it with honey, offering a piece to the house itself.".into(),
                "Walk the home sunwise with rosemary, speaking blessing in each room.".into(),
                "Share the rest of the bread among those who dwell there.".into(),
            ],
            warnings: vec!["Do not forget the offering; a neglected hearth goes quiet.".into()],
            related_entity_ids: vec![130, 3],
            source_note: "Slavic, Norse, and English house-blessing customs.".into(),
            difficulty: 1,
            risk_rating: 1,
            is_custom: false,
            moon_phase: MoonPhaseRequirement::FirstQuarter,
        },
        Spell {
            id: 24,
            name: "Traveler's Blessing".into(),
            category: SpellCategory::Blessing,
            purpose: "Send someone on the road watched, safe, and well supplied.".into(),
            ingredients: vec!["a small sprig of rosemary".into(), "a silver coin".into(), "a pinch of salt".into(), "a white thread".into()],
            steps: vec![
                "Bind the coin, salt, and rosemary in white thread into a small charm.".into(),
                "Hold it and speak the traveller's name and destination aloud.".into(),
                "Hand it to them at the threshold on the day of leaving.".into(),
                "They carry it until safe return, then return it to you to be buried.".into(),
            ],
            warnings: vec!["Do not keep a traveller's charm once they have truly come home.".into()],
            related_entity_ids: vec![3, 8],
            source_note: "Composite of road charms in Norse, Celtic, and Slavic practice.".into(),
            difficulty: 1,
            risk_rating: 1,
            is_custom: false,
            moon_phase: MoonPhaseRequirement::WaxingCrescent,
        },
        // Elemental
        Spell {
            id: 25,
            name: "Quarter Touching".into(),
            category: SpellCategory::Elemental,
            purpose: "Ground, centre, and align your field with the four elemental directions.".into(),
            ingredients: vec!["a bowl of water".into(), "a pinch of salt".into(), "one unlit candle".into(), "incense or a feather".into()],
            steps: vec![
                "Face east with air; breathe and acknowledge movement of mind.".into(),
                "Face south with fire; feel will and courage rise.".into(),
                "Face west with water; let feeling and intuition stir.".into(),
                "Face north with earth; root into bone and stone. Move sunwise and bow.".into(),
            ],
            warnings: vec!["Hold grounding after the final quarter; do not end raw.".into()],
            related_entity_ids: vec![11],
            source_note: "Ceremonial and Wiccan quarter-calling adapted for personal working.".into(),
            difficulty: 2,
            risk_rating: 1,
            is_custom: false,
            moon_phase: MoonPhaseRequirement::Any,
        },
        Spell {
            id: 26,
            name: "Waterline Soothing".into(),
            category: SpellCategory::Elemental,
            purpose: "Work directly with water element to calm storms of feeling.".into(),
            ingredients: vec!["a bowl of spring or rain water".into(), "a blue candle".into(), "a shell or smooth stone".into()],
            steps: vec![
                "Sit before the bowl and breathe into your belly until emotion settles.".into(),
                "Light the blue candle and stir the water sunwise with the shell.".into(),
                "Speak the emotion you wish released into the water, plainly.".into(),
                "Pour the water out at the roots of a living plant.".into(),
            ],
            warnings: vec!["Do not pour into storm drains or running water you drink from.".into()],
            related_entity_ids: vec![133],
            source_note: "Adapted from folk water-appeasement and sea offerings.".into(),
            difficulty: 1,
            risk_rating: 1,
            is_custom: false,
            moon_phase: MoonPhaseRequirement::WaningCrescent,
        },
        // Necromancy
        Spell {
            id: 27,
            name: "Quiet Ancestral Consultation".into(),
            category: SpellCategory::Necromancy,
            purpose: "Ask a known ancestor for advice in a respectful, contained way.".into(),
            ingredients: vec!["a photo or token of the ancestor".into(), "a glass of clean water".into(), "a white candle".into(), "a small offering of food".into()],
            steps: vec![
                "Set the photo before the candle and water at dusk.".into(),
                "Speak their name, ask your question once, and hold silence for ten minutes.".into(),
                "Note any impression that arrives — words, image, memory, pull toward or away.".into(),
                "Thank them, pour water outside, and eat or dispose of the food respectfully the next morning.".into(),
            ],
            warnings: vec!["Only call ancestors you knew or trust reverently.".into(), "Close with thanks; never leave the door open past the rite.".into()],
            related_entity_ids: vec![3, 110],
            source_note: "Ancestor-veneration practice found globally, adapted.".into(),
            difficulty: 3,
            risk_rating: 2,
            is_custom: false,
            moon_phase: MoonPhaseRequirement::WaningCrescent,
        },
        Spell {
            id: 28,
            name: "Graveyard Accord".into(),
            category: SpellCategory::Necromancy,
            purpose: "Request permission and alliance from the spirits of a burial ground before working there.".into(),
            ingredients: vec!["a coin".into(), "a small offering of bread or flowers".into(), "a quiet and steady manner".into()],
            steps: vec![
                "Enter the graveyard at a respectful hour, not midnight by choice.".into(),
                "Find a quiet corner and leave the offering with the coin beneath it.".into(),
                "State who you are, what work you hope to do, and ask leave to proceed.".into(),
                "Listen for agreement before doing anything else; leave without turning back.".into(),
            ],
            warnings: vec!["Never take from a grave without explicit leave.".into(), "If unrest or cold follows you out, do not return until cleansed.".into()],
            related_entity_ids: vec![3, 108, 4, 11],
            source_note: "Necromantic courtesy in European, African diaspora, and Slavic craft.".into(),
            difficulty: 4,
            risk_rating: 4,
            is_custom: false,
            moon_phase: MoonPhaseRequirement::LastQuarter,
        },
        // Other
        Spell {
            id: 29,
            name: "Threshold Oath for New Work".into(),
            category: SpellCategory::Other,
            purpose: "Mark crossing a threshold — new job, moving home, serious change.".into(),
            ingredients: vec!["a key".into(), "a length of red thread".into(), "one small stone from the old threshold".into()],
            steps: vec![
                "Tie the red thread around the key and the old stone together.".into(),
                "Speak aloud what you leave behind and what you intend to build.".into(),
                "Carry the charm through the new threshold first time.".into(),
                "Keep it where you sleep for one moon, then untie and retire the stone respectfully.".into(),
            ],
            warnings: vec!["Threshold oaths bind their maker — speak only what you intend to keep.".into()],
            related_entity_ids: vec![3, 11],
            source_note: "Composite of threshold-magic customs for life passages.".into(),
            difficulty: 2,
            risk_rating: 1,
            is_custom: false,
            moon_phase: MoonPhaseRequirement::NewMoon,
        },
        Spell {
            id: 30,
            name: "Ghost Light".into(),
            category: SpellCategory::Other,
            purpose: "Light a way for a lost person, animal, or wandering spirit to come home.".into(),
            ingredients: vec!["a small white or yellow candle in glass".into(), "a pinch of salt".into(), "a strand of the seeker's hair or favourite belonging".into()],
            steps: vec![
                "Place the candle in a window facing the direction of loss or search.".into(),
                "Set the strand or belonging beside it, and a small dish of salt.".into(),
                "Speak the seeker's name and that light is being kept burning for them.".into(),
                "Let the candle burn a set period each night until they return or the search truly ends.".into(),
            ],
            warnings: vec!["Never use a ghost light to call someone against their will.".into()],
            related_entity_ids: vec![3, 4, 1],
            source_note: "Widow's watch and guiding-light folklore with modern witchcraft adaptation.".into(),
            difficulty: 2,
            risk_rating: 1,
            is_custom: false,
            moon_phase: MoonPhaseRequirement::Any,
        },
        Spell {
            id: 31,
            name: "Name of Sovereignty".into(),
            category: SpellCategory::Other,
            purpose: "Reclaim authority after a period of feeling small, dismissed, or bound.".into(),
            ingredients: vec!["a black or purple candle".into(), "a hand mirror".into(), "a bowl of salted water".into()],
            steps: vec![
                "Gaze at yourself in the mirror by candlelight.".into(),
                "Name aloud the smallness or harm you are ending.".into(),
                "Wash your face and hands in the salted water, turning your palms to the candle." .into(),
                "Speak your full name five times, and keep the mirror nearby for a moon.".into(),
            ],
            warnings: vec!["Do not use to dominate or silence others — sovereignty is self-claimed only.".into()],
            related_entity_ids: vec![1, 105],
            source_note: "Modern witchcraft sovereignty rite drawing on older oath and mirror craft.".into(),
            difficulty: 2,
            risk_rating: 2,
            is_custom: false,
            moon_phase: MoonPhaseRequirement::WaningCrescent,
        },
    ]
}
