use crate::models::Stave;

pub fn build_staves() -> Vec<Stave> {
    vec![
        Stave {
            id: 1,
            name: "To Get a Girl".into(),
            icelandic_name: "Að fá stúlku".into(),
            meaning: "A love stave used by a suitor to win the affections of the one they desire.".into(),
            purpose: "Attraction, love, courtship, romantic pursuit.".into(),
            category: "Love".into(),
            visual_notes: "A small love sigil traditionally drawn or carved onto a token.".into(),
            image_ref: "ic_stave_ad_fa_stulku".into(),
            is_custom: false,
        },
        Stave {
            id: 2,
            name: "Helm of Awe".into(),
            icelandic_name: "Ægishjálmur".into(),
            meaning: "Helm of Terror; induces fear, protects the warrior, and ensures victory in battle.".into(),
            purpose: "Protection in combat, courage, mental domination, warding off enemies.".into(),
            category: "Protection".into(),
            visual_notes: "Eight trident-like arms radiating from a central point, often placed between the brows.".into(),
            image_ref: "ic_stave_aegishjalmur".into(),
            is_custom: false,
        },
        Stave {
            id: 3,
            name: "Mouth-Tapper".into(),
            icelandic_name: "Angurgapi".into(),
            meaning: "Carved on the ends of barrels to prevent them from leaking.".into(),
            purpose: "Household practicality, sealing, preservation.".into(),
            category: "Home".into(),
            visual_notes: "A small sigil inscribed on barrel staves.".into(),
            image_ref: "ic_stave_angurgapi".into(),
            is_custom: false,
        },
        Stave {
            id: 4,
            name: "Whetstone Staves".into(),
            icelandic_name: "Brýnslustafir".into(),
            meaning: "Staves for use on whetstones when sharpening blades.".into(),
            purpose: "Honing tools, sharpening blades, empowering weapons or cutting implements.".into(),
            category: "Craft".into(),
            visual_notes: "Linear stave marks suitable for carving onto a whetstone.".into(),
            image_ref: "ic_stave_brynslustafir".into(),
            is_custom: false,
        },
        Stave {
            id: 5,
            name: "Dream Stave".into(),
            icelandic_name: "Draumstafir".into(),
            meaning: "Used to dream of unfulfilled desires.".into(),
            purpose: "Prophetic dreams, wish-fulfillment in sleep, dream walking.".into(),
            category: "Dreams".into(),
            visual_notes: "A flowing sigil placed beneath the pillow or drawn before sleep.".into(),
            image_ref: "ic_stave_draumstafir".into(),
            is_custom: false,
        },
        Stave {
            id: 6,
            name: "Killing Rune".into(),
            icelandic_name: "Dreprún".into(),
            meaning: "A destructive rune used to kill an enemy's cattle.".into(),
            purpose: "Baneful magic, ruining an enemy's livelihood, cursing livestock.".into(),
            category: "Curses".into(),
            visual_notes: "A sharp, angular sigil from 17th-century grimoires.".into(),
            image_ref: "ic_stave_dreprun".into(),
            is_custom: false,
        },
        Stave {
            id: 7,
            name: "Fetch-Finder".into(),
            icelandic_name: "Feingur".into(),
            meaning: "A fertility symbol preserved in the Huld manuscript.".into(),
            purpose: "Fertility, conception, abundance, new beginnings.".into(),
            category: "Fertility".into(),
            visual_notes: "An intertwined fertility sigil from the Huld Manuscript.".into(),
            image_ref: "ic_stave_feingur".into(),
            is_custom: false,
        },
        Stave {
            id: 8,
            name: "Under-Heel Stave".into(),
            icelandic_name: "Gapaldur".into(),
            meaning: "One of two wrestling staves, worn under the heel of the right foot to ensure victory in glíma.".into(),
            purpose: "Victory, dominance in physical contests, triumph.".into(),
            category: "Victory".into(),
            visual_notes: "A hook-shaped sigil kept in the shoe under the right heel.".into(),
            image_ref: "ic_stave_gapaldur".into(),
            is_custom: false,
        },
        Stave {
            id: 9,
            name: "Under-Toe Stave".into(),
            icelandic_name: "Ginfaxi".into(),
            meaning: "Paired with Gapaldur under the toes of the left foot for victory in Icelandic wrestling.".into(),
            purpose: "Victory in wrestling and combat, strength, sure footing.".into(),
            category: "Victory".into(),
            visual_notes: "A paired sigil placed under the toes of the left foot.".into(),
            image_ref: "ic_stave_ginfaxi".into(),
            is_custom: false,
        },
        Stave {
            id: 10,
            name: "Hill-Opener".into(),
            icelandic_name: "Hólastafur".into(),
            meaning: "Used to open hills, traditionally allowing access to the hidden realms within.".into(),
            purpose: "Accessing hidden places, elf-mounds, earth workings.".into(),
            category: "Spirit Work".into(),
            visual_notes: "A sigil for opening the doorways of hills and mounds.".into(),
            image_ref: "ic_stave_holastafur".into(),
            is_custom: false,
        },
        Stave {
            id: 11,
            name: "Trade-Lock".into(),
            icelandic_name: "Kaupaloki".into(),
            meaning: "To prosper in trade and business.".into(),
            purpose: "Mercantile success, profitable dealings, fair transactions.".into(),
            category: "Prosperity".into(),
            visual_notes: "A commerce sigil drawn on account books or market goods.".into(),
            image_ref: "ic_stave_kaupaloki".into(),
            is_custom: false,
        },
        Stave {
            id: 12,
            name: "Lock-Breaker".into(),
            icelandic_name: "Lásabrjótur".into(),
            meaning: "To open a lock without the need of a key.".into(),
            purpose: "Opening locked doors, removing barriers, escaping bondage.".into(),
            category: "Stealth".into(),
            visual_notes: "A sigil drawn on or near the lock to be opened.".into(),
            image_ref: "ic_stave_lasabrjotur".into(),
            is_custom: false,
        },
        Stave {
            id: 13,
            name: "Lucky Stave".into(),
            icelandic_name: "Lukkustafir".into(),
            meaning: "Whoever carries this symbol encounters no evil on sea or land.".into(),
            purpose: "General luck, safe travel, warding misfortune.".into(),
            category: "Luck".into(),
            visual_notes: "A four-armed cross ending in diamond or looped terminals.".into(),
            image_ref: "ic_stave_lukkustafir".into(),
            is_custom: false,
        },
        Stave {
            id: 14,
            name: "Court-Case Stave".into(),
            icelandic_name: "Máladeilan".into(),
            meaning: "To win in court or prevail in legal disputes.".into(),
            purpose: "Legal victory, successful argumentation, favorable judgment.".into(),
            category: "Victory".into(),
            visual_notes: "A stave carried into court or drawn before proceedings.".into(),
            image_ref: "ic_stave_maladeilan".into(),
            is_custom: false,
        },
        Stave {
            id: 15,
            name: "Necropants Stave".into(),
            icelandic_name: "Nábrókarstafur".into(),
            meaning: "Used when crafting nábrók, magical trousers made from a dead man's skin that produce endless wealth.".into(),
            purpose: "Wealth generation through necromantic craft, dealings with the dead.".into(),
            category: "Spirit Work".into(),
            visual_notes: "A sigil inscribed during the creation of necropants.".into(),
            image_ref: "ic_stave_nabrokarstafur".into(),
            is_custom: false,
        },
        Stave {
            id: 16,
            name: "Terror Stave".into(),
            icelandic_name: "Skelkunarstafur".into(),
            meaning: "To make your enemies afraid. A similar looking stave is titled Óttastafur in the Huld Manuscript.".into(),
            purpose: "Inducing fear in foes, psychological warfare, intimidation.".into(),
            category: "Curses".into(),
            visual_notes: "A sharp, fear-inducing sigil also resembling Óttastafur.".into(),
            image_ref: "ic_stave_skelkunarstafur".into(),
            is_custom: false,
        },
        Stave {
            id: 17,
            name: "Lesser Rose Ring".into(),
            icelandic_name: "Rosahringur minni".into(),
            meaning: "A lesser circle of protection.".into(),
            purpose: "Personal protection, warding, defensive magic.".into(),
            category: "Protection".into(),
            visual_notes: "A protective circle or ring sigil.".into(),
            image_ref: "ic_stave_rosahringur_minni".into(),
            is_custom: false,
        },
        Stave {
            id: 18,
            name: "Butter Knot".into(),
            icelandic_name: "Smjörhnútur".into(),
            meaning: "To reveal whether butter was made with milk stolen by a Tilberi.".into(),
            purpose: "Detecting theft, exposing supernatural trickery, household truth.".into(),
            category: "Home".into(),
            visual_notes: "A small knot-like sigil used with butter or milk.".into(),
            image_ref: "ic_stave_smjorhnutur".into(),
            is_custom: false,
        },
        Stave {
            id: 19,
            name: "Stave Against Sorcery".into(),
            icelandic_name: "Stafur gegn galdri".into(),
            meaning: "Staves against witchcraft and hostile magic.".into(),
            purpose: "Protection from curses, magical defense, counter-magic.".into(),
            category: "Protection".into(),
            visual_notes: "A defensive sigil drawn to deflect hostile spells.".into(),
            image_ref: "ic_stave_stafur_gegn_galdri".into(),
            is_custom: false,
        },
        Stave {
            id: 20,
            name: "Stave to Wake the Dead".into(),
            icelandic_name: "Stafur til að vekja upp draug".into(),
            meaning: "To raise the dead and drive away evil spirits.".into(),
            purpose: "Necromancy, ancestor contact, exorcism of harmful spirits.".into(),
            category: "Spirit Work".into(),
            visual_notes: "A tall staff-like sigil used in grave-mound workings.".into(),
            image_ref: "ic_stave_stafur_til_ad_vekja_upp_draug".into(),
            is_custom: false,
        },
        Stave {
            id: 21,
            name: "Thief's Cross".into(),
            icelandic_name: "Þjófastafur".into(),
            meaning: "For use against thieves and to protect property.".into(),
            purpose: "Protection of property, catching thieves, preventing loss.".into(),
            category: "Protection".into(),
            visual_notes: "A cross with hooked ends often inscribed on doors.".into(),
            image_ref: "ic_stave_thjofastafur".into(),
            is_custom: false,
        },
        Stave {
            id: 22,
            name: "Fox-Ward".into(),
            icelandic_name: "Tóustefna".into(),
            meaning: "To ward off foxes from poultry and livestock.".into(),
            purpose: "Protecting farms, keeping predators at bay, guarding animals.".into(),
            category: "Home".into(),
            visual_notes: "A protective sigil drawn on barns or poultry houses.".into(),
            image_ref: "ic_stave_toustefna".into(),
            is_custom: false,
        },
        Stave {
            id: 23,
            name: "Valdemar's Protection Stave".into(),
            icelandic_name: "Varnarstafur Valdemars".into(),
            meaning: "Increases favor and happiness.".into(),
            purpose: "General favor, happiness, personal blessing.".into(),
            category: "Luck".into(),
            visual_notes: "A circular protective sigil attributed to Valdemar.".into(),
            image_ref: "ic_stave_valdemars".into(),
            is_custom: false,
        },
        Stave {
            id: 24,
            name: "Water Lily".into(),
            icelandic_name: "Vatnahlífir".into(),
            meaning: "Protection against drowning.".into(),
            purpose: "Safety on water, survival at sea, protection from drowning.".into(),
            category: "Travel".into(),
            visual_notes: "A water-associated sigil carved onto boats or carried by sailors.".into(),
            image_ref: "ic_stave_vatnahlifir".into(),
            is_custom: false,
        },
        Stave {
            id: 25,
            name: "Wayfinder".into(),
            icelandic_name: "Vegvísir".into(),
            meaning: "To guide people through rough weather and unknown paths.".into(),
            purpose: "Safe travel, navigation through storms, finding direction.".into(),
            category: "Travel".into(),
            visual_notes: "An eight-pointed compass-rose of stylized runic staves.".into(),
            image_ref: "ic_stave_vegvisir".into(),
            is_custom: false,
        },
        Stave {
            id: 26,
            name: "Fishing Stave".into(),
            icelandic_name: "Veiðistafur".into(),
            meaning: "For luck in fishing.".into(),
            purpose: "Fishing luck, abundance, safe voyages.".into(),
            category: "Prosperity".into(),
            visual_notes: "A fish-luck sigil used by fishermen.".into(),
            image_ref: "ic_stave_veidistafur".into(),
            is_custom: false,
        },
    ]
}
